### ISSUE TITLE
[Suggestion] Option to sort images by upload date instead of ID

### ISSUE THREAD

**Issue by primsdfghjkl** [myimouto/myimouto#128]
I'd like to be able to edit the upload date of each post, and have older posts be further back.

However, posts are sorted by ID, so editing the upload date doesn't change anything.

Is there a way to make it so images are sorted by upload date instead?

**Comment by primsdfghjkl** [comment]
so that worked for me a while ago, but comments seem to be sorted by ID by default. this possible to change?

**Comment by Parziphal** [comment]
That's not possible. Sorting records by `id` is faster, and you don't think someone will want to do this when developing thing kind of things. Heh.
The only solution is, you would have to edit the comments manually in the database. You can set the ids manually there.
