### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#134]
i get everytime after i run the php line:

*** PDOException in PDO#__construct ***
could not find driver
#0 Rails/ActiveRecord/Connection.php(268): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 Rails/ActiveRecord/Connection.php(30): Rails\ActiveRecord\Connection->create_connection(Array)
#2 Rails/ActiveRecord/ActiveRecord.php(65): Rails\ActiveRecord\Connection->__construct(Array, 'production')
#3 Rails/ActiveRecord/ActiveRecord.php(51): Rails\ActiveRecord\ActiveRecord::create_connection('production')
#4 Rails/ActiveRecord/ActiveRecord.php(80): Rails\ActiveRecord\ActiveRecord::setConnection('production')
#5 Rails/Application/Base.php(276): Rails\ActiveRecord\ActiveRecord::set_environment_connection('production')
#6 Rails/Application/Base.php(106): Rails\Application\Base->_load_active_record()
#7 Rails/Application/Base.php(50): Rails\Application\Base->boot()
#8 config/boot.php(29): Rails\Application\Base::initialize()
#9 install.php(7): require('/opt/lampp/htdo...')
#10 {main}
Error context:

**Comment by terokorp** [comment]
do you have php5-mysql installed?

**Comment by Kille250** [comment]
what you mean with pgp5-mysql

**Comment by Kille250** [comment]
ok, have solve it. If somebody have that problem too, type the command: 

apt-get install php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl

You will install all the modules. 

btw you can visit: http://booru.picsofgirls.de

**Comment by terokorp** [comment]
Good, you found the way. I dont think all of those are necessary, but it works.
btw, its not good idea use database as root without password

**Comment by Kille250** [comment]
i know, i will probably change that. But nobody can control my database because the localhost can only login.
