### ISSUE TITLE
upload pictures via url

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#136]
Uploading pictures via url isn't working.
With not working i'm mean, that the full image size isn't saved. Please fix this. You can try this out.

http://booru.picsofgirls.de

**Comment by Ma-ryan** [comment]
I noticed this problem on my install too. Would appreciate a fix.

**Comment by Kille250** [comment]
Yeah, i must download all the pictures before i can upload them...please fix it. :(

**Comment by Parziphal** [comment]
Lol, your comment popping up in the other thread was funny. I'm sorry, I'm not ignoring this (or the many other issues), the thing is that I'm not giving much (not to say nothing at all) support to the project anymore. But, eeh... ok I'll check on this.

**Comment by Kille250** [comment]
@Parziphal and you have found sth? :o

**Comment by Parziphal** [comment]
@Kille250 sorry.
Ok I just tested and... it worked fine... wait no. Alright, gonna fix this.

**Comment by Kille250** [comment]
that was a generated jpg file, if you have seen sth. 
:D I can only say that the pictures are staying at the tmp folder.

**Comment by Parziphal** [comment]
It should work now.

**Comment by Kille250** [comment]
yep. thank you very much. It is a very nice project and you have done nice work so far. :D
