### ISSUE TITLE
How do you edit the menus/HTML?

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#137]
This may be a silly question, but I wanted to add some links to the menus and edit the profile page for users. I'm not sure which files I'm supposed to modify though. Any tips?

**Comment by Parziphal** [comment]
The menu is written in Javascript, and it's in the `app/views/layouts/_menu.php` file. The views for the users pages are under the `app/views/users` folder.

**Comment by Ma-ryan** [comment]
Is the menu cached? My changes do no show up. If so, how do I rebuild the caches?

**Comment by Parziphal** [comment]
Oh yes, it is. Simply empty the `tmp/cache` directory.

**Comment by Ma-ryan** [comment]
OK. Everything is working as expected. Thanks a lot!

**Comment by Parziphal** [comment]
You're welcome~
