### ISSUE TITLE
[Major Security Hole] Javascript In Tag Search

### ISSUE THREAD

**Issue by Vanndril** [myimouto/myimouto#138]
A user on my site found a similar injection issue to #133 with the tag search feature. His/her exact words were...

>I can search for a string of Javascript in tags (with < script >javascripthere< /script >) and it will execute the javascript.

Whether he meant the Posts tag search box or literally searching tags in the Tag Database is not known to me. Asked him and waiting on a reply. Will edit and tell when I know.

Centos 6.5 / PHP 5.5.12 / Nginx 1.0.15 / mysql Ver 14.14 Distrib 5.5.31
Booru Version: 1.0.6

**Comment by Parziphal** [comment]
Wait, that wasn't enough...

**Comment by Vanndril** [comment]
Thank ye, thank ye. With two of these similar holes found recently, my more tech savvy users seem to be on a hunt for even more of 'em. I'll let you know if anything further comes up.

I'll close the ticket here for now, reopening it if a problem arises with the fixes or some such.

**Comment by Vanndril** [comment]
Ah, so, as it turns out, the issues don't seem to be entirely fixed!

To note and clarify, the original report was of the post search.

Here's a little something to see. The whole gig is a little bit beyond me, but I can at least say that something's a little odd in these searches.

http://hypnohub.net/post?tags=%3C%2Ftitle%3E%3Cscript%3Ealert%280%29%3B%3C%2Fscript%3E

http://hypnohub.net/post?tags=%22+%2F%3E%3Cscript%3Ealert%280%29%3B%3C%2Fscript%3E

**Comment by rupaheizu** [comment]
@Vanndril an hour later @Parziphal merged #135 which would fix that issue.

**Comment by Vanndril** [comment]
@rupaheizu - Nada. I already had that fix implemented before the merge for security (and testing) reasons. The problem still occurs when Javascript is used in the post page's search bar.
