### ISSUE TITLE
[Question/Suggestion] IPv6 And IP Banning

### ISSUE THREAD

**Issue by Vanndril** [myimouto/myimouto#139]
At a glance, it doesn't look like IPv6 is supported in the IP banning system. Any chance this could be implemented, or that I'm wrong and it's already supported? We have quite a few users that use IPv6 addresses, and it dawns on me that I'm likely to be unable to reliably ban them if it comes down to that.

When I try to add an IPv6 address to the IP ban system, it seemingly cuts off every character after the 15'th, which is the length of an IPv4 address.

**Comment by rupaheizu** [comment]
On it.
