### ISSUE TITLE
editor/custom buttons

### ISSUE THREAD

**Issue by RobHones** [myimouto/myimouto#140]
I think it would be good to add an editor like TinyMCE to myimouto.
I have ... kind of ... had a quick look myself but I'm not to sure where to start?
Does anyone have any idea where I should add the script for the editor? I would want it for all the text areas (comment, forum) so I can use custom buttons for the Dtext like spoiler tags etc.
Any help or other ideas would be great.

**Comment by Parziphal** [comment]
You can place the TinyMCE files in `app/assets/javascripts`, then find and edit the corresponding views in `app/views`, then you would have to recompile assets files... that's more or less it. But doesn't TinyMCE output HTML? The HTML tags will be stripped out. I actually don't think it will be a good idea to implement it.

**Comment by RobHones** [comment]
It wouldn't be the full editor that I would try to implement just the customized buttons to quickly insert dtext tags it might actually be better starting from scratch I suppose. I was under the impression you could have buttons on tinymce that would output custom code but you are probably write they could still be wrapped in html tags. I might give it a quick experiment just to see what happens.

**Comment by Parziphal** [comment]
How about you craft buttons for the not-so-many formatting options allowed/available? I don't think it'd be hard. Actually, that would be nice.

**Comment by Kille250** [comment]
@Parziphal can you help me with the url upload funcion? Or you want to ignore it anyway?
