### ISSUE TITLE
Danbooru style

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#141]
how can i activate the "danbooru style" option?

**Comment by Parziphal** [comment]
That "feature" was "removed" very, very long time ago.

**Comment by Kille250** [comment]
oh man. :( Is it possible to edit the css files? If yes, could you explain me what to edit exactly because i don't was having luck.

**Comment by Parziphal** [comment]
You would need to read this guide: https://code.google.com/p/my-imouto-booru/wiki/HowToUse#Assets

**Comment by Kille250** [comment]
i will try that out.

**Comment by Kille250** [comment]
you can close that issue. :)
