### ISSUE TITLE
Official mp4 support

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#143]
Would be awesome to implement the mp4 support. I have added that on the code but thumbnails don't want to be generated and the filesize doesn't want to get readed. I know that you don't are working on this project anymore but it would be awesome. :D

**Comment by Parziphal** [comment]
If I could duplicate myself, believe me I'd work 24/7 on this project.

**Comment by Kille250** [comment]
i read all you'r articles from you'r blog now. I want to now more about this project. xD

**Comment by Parziphal** [comment]
You want to know more? Know what?

**Comment by Kille250** [comment]
how you started from the beginning to the end.

**Comment by Parziphal** [comment]
Oh. Yeah the story is there.
Thanks for reading, by the way.

**Comment by Kille250** [comment]
no problem. It's a interesting story. :D

**Comment by Kille250** [comment]
I don't believe that this feature will be released soon, or i am wrong? xD

**Comment by Parziphal** [comment]
Actually, MyImouto development stopped before this request. So don't be surprised if mp4 support never gets implemented. I'm sorry.

**Comment by Kille250** [comment]
I would be so happy, "the last feature or sth, but you've done great work!
Thanks you for that.
Am 04.06.2016 20:58 schrieb "Pop" <notifications@github.com>:

**Comment by Kille250** [comment]
And one question. How i can onfigure that all peope under the rank contributor are automatically submit pictuers with the status pending. I have tryed to max out the min_mpixels. If i am doing that a normal account can't upload a picture.

**Comment by Parziphal** [comment]
You can do that in `app/controllers/PostController.php`. On line `35`, under the `create` method, you'll see:

```php
if (current_user()->is_privileged_or_higher()) {
    $status = "active";
} else {
    $status = "pending";
}
```

Change that condition to fit your needs. If you want members from contributors down (i.e. contributors, privileged and member) to have their posts tagged with "pending", change the condition to this:

```php
if (current_user()->is_janitor_or_higher()) {
```

With that condition only janitors, mods and admins will have their posts set to active automatically.

But maybe (just maybe) you'd want to activate privileged's and up posts, except contributors'... in that case you can do this:

```php
if (current_user()->is_privileged_or_higher() && !current_user()->is_contributor()) {
```
