### ISSUE TITLE
hidden tag's

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#144]
i can't remove the tag "loli" from the index. After enable the option, the pictures get removed and everywhere i get the message the their aren't any pictures on the database.

**Comment by Kille250** [comment]
can you help me pls? :o

**Comment by Parziphal** [comment]
Can please you explain further, a little more clear?

**Comment by Kille250** [comment]
Sorry. I have change this.

public function can_see_post(\User $user, \Post $post) 
{  
if($post->has_tag('loli') && $user->is('>=40')) return true; 
    }

This isn't working. All post are disappearing if i change this.

**Comment by Kille250** [comment]
you know why?

**Comment by Parziphal** [comment]
Sorry, I'm usually away on weekends.
Ok so you wanna hide the posts with `loli` tag from the index. That condition is incomplete, actually. It should be like this:

    if ($post->has_tag('loli')) {
        if ($user->is_mod_or_higher() {
            return true;
        } else {
            return false;
        }
    }
    return true;

That makes more sense.
Now, for this to work, I had to make a fix. The `Post::has_tag()` method wasn't working (always returned false), and also the example code is incredibly outdated (the `User::is()` method was removed long ago).
I'll push the changes. Thanks for pointing out those errors~

**Comment by Kille250** [comment]
i'm dumb. You'r right. It's more logical. btw, it's working now. Thanks you very much and sorry if i make to mutch trouble or requests. xD

**Comment by Parziphal** [comment]
It's fine, sorry for responding slowly.

**Comment by Kille250** [comment]
It isn't working again. xD

if ($post->has_tag('loli') && !$user->is_mod_or_higher()) {
    return false;
}
return true;

If i change it to that everything is gone. ,-,

**Comment by Parziphal** [comment]
What happens? is any error logged or something?

**Comment by Kille250** [comment]
lol, if i set up this, everything is showing up now.

if ($post->rating == 'e' && $user->is_member_or_higher()) {
return false;
}
          return true;

The logs are saying nothing about that. Maybe i am just dumb. xD

**Comment by Kille250** [comment]
Nvm got it
