### ISSUE TITLE
No auto-tagging, all tagged as "tagme"

### ISSUE THREAD

**Issue by inVech** [myimouto/myimouto#145]
Hello,
Basically I've already tried with 3 myimouto installations, basically no image gets auto tagged, whether from upload or import. I even tried using search for external data, and in the "search found" all it gives is "Server: http://iqdb.yande.re/index.xml; Message: [object Object]", I attempted importing 1000 images, and non were tagged. The file names in import are named "Konachan.com - 160219 armor blonde_hair forest scenic tree.jpg" for example.

And as I said in the title, everything is just tagged "tagme"

**Comment by Kille250** [comment]
to auto tagging it, you must run the job_tasks.

**Comment by inVech** [comment]
This might a stupid question, but how do I run job_tasks? I had a installation of myimouto on my previous windows installation, and everything was just automatically tagged

**Comment by inVech** [comment]
Never mind, I'll simply read http://code.google.com/p/my-imouto-booru/wiki/WhatIsMyImouto

**Comment by Parziphal** [comment]
Wait a minute, you don't need to run job tasks in order to get images tagged automatically.

**Comment by Kille250** [comment]
but how is it than possible? :o

**Comment by Kille250** [comment]
i need to read more about this project. xD

**Comment by Parziphal** [comment]
You said your images are named "Konachan.com - 123 tag_1 tag_2", and that tags aren't taken out of file names. That's correct, unless you've edited the `filename_to_tags()` method in your configuration. Have you edited that method? Because, as the about-wiki says: `By default, all images from moe|oreno|yande.re are automatically detected.`. Your images are from Konachan.

**Comment by Kille250** [comment]
ah yes. The tags should be added automatically if you have wrote it after the filename. >.<

**Comment by inVech** [comment]
I haven't edited the filenametotags at all, I tried with 3 fresh installations

**Comment by Parziphal** [comment]
You have to edit the method. It should look like this:

    if (preg_match("/^(?:yande\.re|moe|Konachan\.com -) \d+ (.*)$/", $filename, $m)) {
        return array_filter(array_unique(explode(' ', $m[1])));
    }

That should now detect names starting with `Konachan.com -`.

**Comment by inVech** [comment]
I'll try that, thank you. Although I still wonder how come my previous windows' installation tagged them all automatically, without me changing the method?

**Comment by Parziphal** [comment]
Mmm, I have no idea, hehe. Probably a bug or error that got fixed. But since always (AFAIR), one is supposed to edit that method to fit their needs.

**Comment by Kille250** [comment]
to start the job_tasks you must change the myimouto_dev in the databse file to you'r databse name.

**Comment by inVech** [comment]
Alright, once again, thanks a bunch, both of you.

**Comment by Kille250** [comment]
yeah, i do my best. xD
