### ISSUE TITLE
e-mail function

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#146]
Everytime it says that the email isn't registered on the account or other error messages. But it is in the database. If i want to change my password via the function it says, "Delivery to this email address has failed." Can you help me to set this up?

**Comment by Kille250** [comment]
Edit: I got now, "Your email address was invalid". I looked into the database and i have typed it like there. The problem occurres every time.

**Comment by Kille250** [comment]
@Parziphal can you help me with that? Sorry for all the notifications on you'r mobile probably. xD

**Comment by Parziphal** [comment]
Are you sure your server can deliver emails?

**Comment by Kille250** [comment]
how can i test it? xD

**Comment by Parziphal** [comment]
Are you running your booru locally or in a server?

**Comment by Kille250** [comment]
http://moebooru.org

on a server. :)

**Comment by Parziphal** [comment]
Moebooru? Intersting name...
Is any error logged regarding this?

**Comment by Kille250** [comment]
wait i've readed that the admin-email account will be used for sending emails? or is it false?

**Comment by Parziphal** [comment]
Where did you read that?

**Comment by Kille250** [comment]
i think in a php file. But don't know right now which. But maybe i say sth
wrong.

**Comment by Parziphal** [comment]
I just remembered that you have to configure the framework to tell it which way you want it to use to deliver emails.

**Comment by Kille250** [comment]
ah sorry. I'm learning right now php and i try to understand the language.
For which way is it right now configured? Or how i can configure it? Sorry
for all the questions.

**Comment by Parziphal** [comment]
I already forgot about configurations and thigs. I had to check the files.
Well it seems like the default delivery method is `sendmail` which should work fine in any server.
Have you checked for errors logged regarding resetting your password? I just checked the code and the message "Your email address is invalid" is shown upon any kind of error (which is a shame) but... Mmm it looks like the error isn't logged... we have a problem here. Check for logged errors anyway.

You could also make sure your server can deliver emails in a simple PHP file. Try with the example shown here: http://php.net/manual/en/function.mail.php

**Comment by Kille250** [comment]
Nope, don't have found an error.

**Comment by Parziphal** [comment]
Ok let's try this...

Open the file `app/controllers/UserController.php`. Go to the line 322, you should see:

    } catch (Exception $e) { // rescue Net::SMTPSyntaxError, Net::SMTPFatalError

Below that, enter this:

    Rails::log()->exception($e);

Try to send your email again and then check the error log.

**Comment by Kille250** [comment]
this command stands for? I think it is forcing to write the log. or i am wrong?
Anyway, here's the log.

[11-Feb-2015 17:44:17 CET] [88.153.155.30] POST /user/reset_password.json
Zend\Mail\Exception\RuntimeException in Zend\Mail\Transport\Sendmail#mailHandler
Unable to send mail: Unknown error
#0 [internal function]: Zend\Mail\Transport\Sendmail->mailHandler('Dionyssioss@gma...', 'moebooru - Pass...', 'This is a messa...', 'Date: Wed, 11 F...', ' -fDionyssioss@...')
#1 vendor/zendframework/zend-mail/Zend/Mail/Transport/Sendmail.php(139): call_user_func(Array, 'Dionyssioss@gma...', 'moebooru - Pass...', 'This is a messa...', 'Date: Wed, 11 F...', ' -fDionyssioss@...')
#2 Rails/ActionMailer/Deliverer.php(50): Zend\Mail\Transport\Sendmail->send(Object(Zend\Mail\Message))
#3 app/controllers/UserController.php(317): Rails\ActionMailer\Deliverer->deliver()
#4 Rails/ActionController/Base.php(268): UserController->resetPassword()
#5 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('resetPassword')
#6 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#7 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#8 public/index.php(3): Rails\Application\Base::dispatchRequest()
#9 {main}
Error context:
array(5) {
  [0]=>
  string(21) "Dionyssioss@gmail.com"
  [1]=>
  string(25) "moebooru - Password Reset"
  [2]=>
  string(744) "This is a message in Mime Format.  If you see this, your mail reader does not support this format.

--=_8182398ecff27bd9c826103bb38ea9e4
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

Hello, picsofgirls. Your password has been reset to:=0A=0A   pisuquba97=
=0AYou can login to http://moebooru.org/user/login and change your passw=
ord to something else.=0A
--=_8182398ecff27bd9c826103bb38ea9e4
Content-Type: text/html
Content-Transfer-Encoding: quoted-printable

Hello, picsofgirls. Your password has been reset to pisuquba97.=0A=0AYou can login to moebooru and change your password to something else.=0A
--=_8182398ecff27bd9c826103bb38ea9e4--"
  [3]=>
  string(168) "Date: Wed, 11 Feb 2015 17:44:17 +0100
From: Dionyssioss@gmail.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_8182398ecff27bd9c826103bb38ea9e4"
"
  [4]=>
  string(24) " -fDionyssioss@gmail.com"
}

**Comment by Parziphal** [comment]
That line of code (I don't think that's called a command), or you could say, that method call, what it does is just to log an exception. It doesn't "force" anything, you can call it every time, anywhere you need it. The code is lacking that line of code, because logging errors is very useful.

Ok back to the log... the log doesn't help either (I know I said logging errors is very useful. It is... most of the time). As you can see, Zend says `Unknown error`. Thanks Zend.
Only thing left is to check if your server can actually send emails. Please try with the example in the PHP manual linked above.

**Comment by Kille250** [comment]
okay, i will.

**Comment by Kille250** [comment]
yep, it isn't working. I read that the sendmail function isn't activated on xampp. I invastigate now, how i can activate it on ubuntu.

**Comment by Parziphal** [comment]
You can also configure the system to send mails using an email account of yours, for example with Gmail.

**Comment by Kille250** [comment]
i sit now 1 hour to find that. how? xD

**Comment by Parziphal** [comment]
Open the `config/environments/production.php` file and enter the following below line 11:

    $config->action_mailer->smtp_settings = [
        'address'        => 'smtp.gmail.com',
        'port'           => 587,
        'domain'         => 'yourdomain.com', // This doesn't matter
        'user_name'      => 'your_address@gmail.com',
        'password'       => 'your_email_password',
        'authentication' => 'plain',
        'enable_starttls_auto' => true // Requires openssl PHP extension.
    ];

As we can see the comment above, it seems like you have to enable the openssl PHP extension.

**Comment by Kille250** [comment]
get, "Delivery to this email address has failed." Isn't working.

**Comment by Parziphal** [comment]
Any logged error?

**Comment by Kille250** [comment]
no, on the other board the email reset option is working. But why isn't that on my.. i don't understand what i am doing wrong.

**Comment by Parziphal** [comment]
Other board of yours?

**Comment by Kille250** [comment]
no, on this. 

http://hypnohub.net/

**Comment by Parziphal** [comment]
Oh well, they have a well set-up server, with all things a server needs. I can't guide you through setting up an email server because I simply don't know how to (I don't know much about server-related stuff). I think it's not too easy or possible for everyone.
But the SMPT deliver method should work for you. Make sure you have the OpenSSL PHP extension enabled.

**Comment by Kille250** [comment]
i have it activated on the php.ini. But thanks anyway for trying it. :)

**Comment by Kille250** [comment]
now i am stuck on running it on nginx. I must learn a lot. xD

**Comment by Parziphal** [comment]
I remember I had the configuration for nginx but I can't find it.

**Comment by Kille250** [comment]
oh. It's all right. It's quite fun to try to configure it. :D But on the other side...xD

**Comment by Kille250** [comment]
@parziphal have installed nginx with the php framework. One problem occurs. Can't connect with my database. Because that i have installed postgresql but i got the same error.

**Comment by Kille250** [comment]
ok, i got it. I have run install.php and all is installed. Now i need you'r help. Redirecting and showing images isn't working. I don't know what i have done wrong in the config.

**Comment by Parziphal** [comment]
Are you using nginx? You need to writes the corresponding redirecting rules in order to make it work.

**Comment by Kille250** [comment]
i know. And the .htaccess file is now useless?

**Comment by Parziphal** [comment]
Yes. You need to pass those rules into nginx. How? I don't remember.

**Comment by Kille250** [comment]
i edit the rules in the nginx.conf. But i don't know if it must be there.

**Comment by Kille250** [comment]
i don't find the mistake. 
```
rewrite ^/(?:data/)?(preview|sample|jpeg|image)/([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{28})(?:/.*?)?(\.[\w]+)$ /data/$1/$2/$3/$2$3$4$5 last;
if (-f $request_filename){
	set $rule_0 1;
}
if ($rule_0 = "1"){
	rewrite ^/(assets/.*)\.css /$1\.css\.gz last;
}
if (-f $request_filename){
	set $rule_1 1;
}
if ($rule_1 = "1"){
	rewrite ^/(assets/.*)\.js /$1\.js\.gz last;
}
try_files $uri /index.php$is_args$args;
```

**Comment by Parziphal** [comment]
I don't know Nginx so... I don't really know what could be wrong.

**Comment by Kille250** [comment]
and you don't find you'r old configurations? :(

**Comment by Parziphal** [comment]
I searched and couldn't find it.

**Comment by Kille250** [comment]
mh...don't know how i can do that.

**Comment by Parziphal** [comment]
You can find NGINX rules in the Ubuntu installation wiki.
I know, I'm 18 months late.
