### ISSUE TITLE
[Question] Current State of the Project?

### ISSUE THREAD

**Issue by Vanndril** [myimouto/myimouto#152]
I apologize if this information is readily available somewhere. If it is, I've not found it.

I know that around 10 months ago this software project was put on hold. According to the blog, someone else was to pick it up. Beyond that, I know little of the current situation of the My Imouto Booru software.

The users of my site, which runs strictly on this software and has for nearly two years, have become worried that the site is running on "vaporware". I'd just like information to either confirm or deny this fact, so that we can more clearly grasp the situation. As such, I ask:

Is this software currently being developed?

I also heard word - once again, many months ago - of a supposed rewrite of this software being in the works. Is this new project still ongoing?

I thank you ahead of time, whoever replies, for an answer regarding the intended future of this software.

**Comment by Parziphal** [comment]
Your message, I can feel the uncertainty, the sorrow, the worry, because this was a happy, prosperous and very active project, but its life had to take a turn and now it's like a ghost town where you can only see the remains of what once was an active workshop.

Or something like that.

The status is, sadly, what your people say. Although I don't exactly know what vaporware is. The project is not being developed by anyone. I'm not even fixing errors. The person who said was working on something never replied again.

The rewrite is neither being worked on. Let's just say it straight away: the project is dead.

I said in the last issue that I wish I could rewrite My Imouto, because the project is very outdated and it cries for the use of new web technology, but I don't have time, nor the energy to do so. It's a very big system. Rewriting it would be a very big job. All the logic, all the javascript. It's just huge. If I had free time I would just do it for what this project means to me. *shades manly tears*

**Comment by Vanndril** [comment]
I appreciate the answer (and, of course, the theatrics - nay, especially the theatrics!).

Vaporware is, essentially, software which was never fully completed and is no longer in development despite having been publicly released. It's running on fumes, so to speak; thus the term.

This is sad news, indeed. From it, I hear the cries of the poor souls who wished for this software to be great as their hopes burn in the fiery depths below. Their anguish reaches my ears in a form most bare. Alas, what was once a wonderful ideal has been reduced to ash.

Or something like that. ;)

In any case, I thank you for the swift answer. This is most...disconcerting for the future of my site. It looks like my users and I have some big decisions to make regarding the future of the site. But that is neither here nor there, nor is it something you need concern yourself with.

I do, of course, respect your decision to move on. I fully understand how difficult it is to leave a pet project such as this. Thank you for your support for the two years during which we've been using your software. Your efforts were most appreciated. I wish you luck in whatever new projects claim your attention.

I will continue to report bugs as they arrive for as long as we continue to use the software, however, in case someone does take up the mantle someday.

**Comment by jewyti** [comment]
I'm new here and kinda support the idea of the continuing the project but I may need also inputs on what technologies we may be using for a compromise for future contributors. I know it's hard to maintain a project only the project owner knows so much about we could change things for the better.

Just to make it sure, are we moving on? Like to another framework? Or keep this going?

**Comment by Parziphal** [comment]
Oh, I went to sleep right after I commented. I felt sad somehow, even though I was joking. Anywat, the news can be edited in `app/views/layouts/_notice.php` if I'm not wrong.

jewyti, even if I chosed a popular framework, only those who dive into the code would know as much as me (and anyone who knows Moebooru, too)

**Comment by Parziphal** [comment]
Whoops I pressed the close and comment button on mistake (I'm on the phone). So... what I had in mind was to use Laravel 5 and Angular for the rewrite.
But a full rewrite, using HTML5 and responsive design... that's a huge proyect!

**Comment by jewyti** [comment]
If you have a repository to work on tag me :)

**Comment by Cael** [comment]
I can't offer a lot of time but if we get something going I'd be more than
happy to contribute at least a little bit. It's been a whole since I've had
a pet project.

**Comment by Vanndril** [comment]
Anyway, the news can be edited in app/views/layouts/_notice.php if I'm not wrong.
It was _news.php in the same folder, actually. Thanks, though. You led me to the right answer. I would have never thought to look in this folder.

**Comment by Parziphal** [comment]
Current status: fixing errors reported over 1.5 years ago and closing old issues.
