### ISSUE TITLE
[Dev] Technologies to use

### ISSUE THREAD

**Issue by jewyti** [myimouto/myimouto#153]
Instead of using Laravel which may be heavy overall. I propose a lighter solution in using *Lumen*, it's still Laravel but a lot lighter and gives will enable the project to be more modular allowing *plugins so to say* to thrive.

**Comment by Parziphal** [comment]
Looks good. I'd try it in my job but it seems like you have to manually configure everything. So I'll try to try it out whenever I can.

**Comment by jewyti** [comment]
It's more of a power user kind of framework; I'll also look around for alternatives, maybe create some libraries we can use for the project to make it easier.

**Comment by Parziphal** [comment]
Lumen has been changed to be framework for API with stateless auth. So... this is no longer a valid solution.
<sub>lol over a year later</sub>
