### ISSUE TITLE
[Issue] Uploaded images not showing

### ISSUE THREAD

**Issue by jewyti** [myimouto/myimouto#154]
Recently I've installed a fresh copy in http://myimouto.henyaku.moe. I experienced this bug by successfully uploading an image and viewing the `show` or the `index`, the image will result to a `404` which is caused by the lacking `$this->_file_hierarchy()` in `app/models/Post/ImageStore/LocalHierarchy.php` on line 14.

**Comment by Parziphal** [comment]
Under correct configuration you shouldn't have this problem; I don't have this problem. The first `.htaccess` rule (if using Apache) should redirect the current `file_url()` (e.g. `http://myimouto/data/image/1d25eb68fb354955bcfc700460244054.jpg`) to the correct file location (e.g. `http://myimouto/data/image/1d/25/1d25eb68fb354955bcfc700460244054.jpg`). So either you're not under Apache or there's something wrong with its configuration?

**Comment by jewyti** [comment]
Oh shit this must be the old commit. Lemme fix it, I'm using Nginx by the way. I'll edit the documentation also for the Nginx setup

**Comment by Parziphal** [comment]
lol~
I had the configuration for Nginx but I don't remember where I saved it.

**Comment by Ninn0x4F** [comment]
Do you still have the nginx configuration? Since im hating using apache overall,
Currently using this on nginx but it's kinda well not working properly since batch and import not working, also uploading shows not the images...

    location / {
    try_files $uri $uri/ /index.php;
    }
    
    location ^~ /assets/ {
    gzip_static on;
    }
    
    location ~ \.php$ {
    try_files $uri /index.php;
    # other PHP fastcgi stuff
    }

**Comment by jewyti** [comment]
@Ninn0x4F Currently trying to fix the batch uploading, there are some few scratches on the file hierarchy that makes no sense. And will put up a pull request by the next day or two.

This is my bare bone setup
```
server {
  listen 80;
  server_name myimouto.henyaku.moe;
  root /srv/myimouto/public;
  index index.php;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~* \.php$ {
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    fastcgi_split_path_info ^(.+\.php)(.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME $fastcgi_script_name;
  }
}
```

**Comment by Ninn0x4F** [comment]
@jewyti Strange it's working if im not logged in, but after logging in it's just throwing up the 404 page, also there is an difference between the account "login" page, for me it's just throw's up this http://puu.sh/iqRO6/8cbdc7a53a.png and if im trying to create an account on your booru it's working like it should, after login in my booru it's throwing up the 404 page, have to clear cookies to work again. On Apache it's working fine, but on nginx it's have some difficulties, my conf looks like yours, except for the configuration im using an panel "ajenti"

    server {
    listen *:80;


    server_name domain.com www.domain.com;

    access_log /var/log/nginx/$domain.access.log;
    error_log /var/log/nginx/$domain.error.log;

    root /srv/domain.com/public;
    index index.html index.htm index.php;

    location / {
    try_files $uri $uri/ /index.php?$query_string;
    }



    location ~ [^/]\.php(/|$) {



        fastcgi_index index.php;
        include fcgi.conf;
        fastcgi_pass unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.$
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    }

    }

**Comment by Parziphal** [comment]
You can find the NGINX configuration in the Ubuntu install guide wiki page.
