### ISSUE TITLE
Trouble compiling assets

### ISSUE THREAD

**Issue by primsdfghjkl** [myimouto/myimouto#156]
I want to edit the stylesheets in my installation, and I'm going by another post (https://github.com/myimouto/myimouto/issues/46), but whenever I try to compile assets manually, I receive the following:
http://puu.sh/iJ3kq/752a9df6ee.png

...and if I switch to development mode, there are just no stylesheets whatsoever - everything appears over a white background.

What should I do?

Also, while I'm at it, what would I edit to give a custom tag type its own color once I'm able to modify the stylesheets?

**Comment by Parziphal** [comment]
What PHP version are you using?

**Comment by primsdfghjkl** [comment]
5.5.11

**Comment by jewyti** [comment]
Also getting this error with the same PHP version on Mac. Trying to find a workaround also

**Comment by Kille250** [comment]
[ErrNo 8192]: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead 
#0 [internal function]: Rails::errorHandler(8192, 'preg_replace():...', '/opt/lampp/htdo...', 324, Array)
#1 vendor/toopay/assetic-minifier/src/Minifier/Cssmin.php(324): preg_replace('/(text-shadow\:...', 'strtolower('$1 ...', '@charset "___YU...')
#2 vendor/toopay/assetic-minifier/src/Minifier/Cssmin.php(137): Minifier\CSSmin->minify('@charset "___YU...', false)
#3 Rails/Assets/Assets.php(509): Minifier\CSSmin->run('@charset "UTF-8...')
#4 Rails/Assets/Assets.php(336): Rails\Assets\Assets->compressFile('@charset "UTF-8...', 'css')
#5 Rails/Assets/Assets.php(196): Rails\Assets\Assets->compileFile(Object(Rails\Assets\File))
#6 Rails/Console/ApplicationConsole.php(56): Rails\Assets\Assets->compileAll()
#7 Rails/Application/Base.php(53): Rails\Console\ApplicationConsole->run()
#8 config/boot.php(29): Rails\Application\Base::initialize()
#9 {main}
Error context:

same here

**Comment by Parziphal** [comment]
I updated the framework to use the last version of the CSS minifier which fixes this error.
