### ISSUE TITLE
incompatible with the Zend Load

### ISSUE THREAD

**Issue by jblgf** [myimouto/myimouto#158]
incompatible with the Zend Load with the configuration
zend_loader.obfuscation_level_support = 3 & 2
PHP - v5.4.43
log with error

[20-Jul-2015 16:19:25 BRT] [127.0.0.1] GET /
Rails\Loader\Exception\FileNotFoundException in Rails\Loader\Loader#loadClass
Couldn't find file for class v60uhx, searched for v60uhx.php in:
/server/servidor3/teste47/myimouto/vendor/railsphp/railsphp/lib
/server/servidor3/teste47/myimouto/app/models
/server/servidor3/teste47/myimouto/app/helpers
/server/servidor3/teste47/myimouto/app/controllers
/server/servidor3/teste47/myimouto/app/mailers
/server/servidor3/teste47/myimouto/lib
/server/servidor3/teste47/myimouto/vendor
#0 [internal function]: Rails\Loader\Loader->loadClass('v60uhx')
#1 [internal function]: spl_autoload_call('v60uhx')
#2 Rails/ActiveRecord/Relation/AbstractRelation.php(526): defined('IpBans::connect...')
#3 Rails/ActiveRecord/Relation/AbstractRelation.php(544): Rails\ActiveRecord\Relation\AbstractRelation->_set_model_connection()
#4 Rails/ActiveRecord/Relation/AbstractRelation.php(77): Rails\ActiveRecord\Relation\AbstractRelation->executeSql()
#5 Rails/ActiveRecord/Relation/AbstractRelation.php(177): Rails\ActiveRecord\Relation\AbstractRelation->take()
#6 app/controllers/ApplicationController.php(217): Rails\ActiveRecord\Relation\AbstractRelation->first()
#7 app/controllers/ApplicationController.php(227): ApplicationController->get_ip_ban()
#8 Rails/ActionController/Base.php(464): ApplicationController->check_ip_ban()
#9 Rails/ActionController/Base.php(230): Rails\ActionController\Base->runFilters('before')
#10 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#11 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#12 public/index.php(3): Rails\Application\Base::dispatchRequest()
#13 {main}
Error context:
array(1) {
  [0]=>
  string(6) "v60uhx"
}

**Comment by Parziphal** [comment]
You can use Composer for loading classes.
