### ISSUE TITLE
Any way to give mods/contributors access to the import feature?

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#161]
I'd like to give a user access to it without giving him admin powers. Is this possible somehow?

**Comment by Parziphal** [comment]
Go to `app/controllers/PostController.php`, search for the `protected function filters()` (it's at the bottom of the file), and then find this line:

    'admin_only' => ['only' => ['import']],

The `admin_only` string is the one you'll like to change. To allow contributors and higher ranks to access this section, set `contributor_only`.

**Comment by Ma-ryan** [comment]
All right. Thanks! It worked. I also had to similarly edit _menu.php to make the link show up in the menu.
