### ISSUE TITLE
[Issue] Getting external data does not work in all cases

### ISSUE THREAD

**Issue by xkomachi** [myimouto/myimouto#162]
Issue summary:
When trying to get external data from a post( http://127.0.0.1:*port*/post/search_external_data?ids=*postid* ,or via job_tasks),some posts don't successfully get the data and instead show "An error occured" in the search results and "There was an error with post #postid" pops at the top of the page. This does not happen for all pictures (some can fetch data correctly).
For reference,here is the image used for this issue:
https://cloud.githubusercontent.com/assets/15238891/10671150/bd525d5a-78f1-11e5-89b5-7a08f7ab4b63.jpg

Here's the relevant section from /log/production.log:

[22-Oct-2015 18:57:59 IDT] [127.0.0.1] POST /post/similar.json
PHP Warning in SimilarImages::{closure}
SimilarImages::{closure}(): Node no longer exists 
#0 C:\myimouto\lib\SimilarImages.php(124): Rails::errorHandler(2, 'SimilarImages::...', 'C:\\myimouto\\lib...', 124, Array)
#1 C:\myimouto\lib\SimilarImages.php(185): SimilarImages::{closure}(Object(SimpleXMLElement), 'id')
#2 C:\myimouto\app\controllers\PostController.php(847): SimilarImages::similar_images(Array)
#3 C:\myimouto\app\controllers\PostController.php(852): PostController->{closure}(Array)
#4 C:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActionController\Base.php(268): PostController->similar()
#5 C:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActionController\Base.php(238): Rails\ActionController\Base->runAction('similar')
#6 C:\myimouto\vendor\railsphp\railsphp\lib\Rails\Application\Base.php(188): Rails\ActionController\Base->run_request_action()
#7 C:\myimouto\vendor\railsphp\railsphp\lib\Rails\Application\Base.php(39): Rails\Application\Base->_run()
#8 C:\myimouto\public\index.php(3): Rails\Application\Base::dispatchRequest()
#9 {main}
Error context:
array(2) {
  ["xml"]=>
  object(SimpleXMLElement)#312 (0) {
  }
  ["attr"]=>
  string(2) "id"
}

The similar image search (http://127.0.0.1:*port*/post/similar) for the same image does not work either: You get the general "An error has occurred." page (the one with /public/images/errors.png).
The log is almost identical,except for this line
object(SimpleXMLElement)#312 (0) {
changing to this:
object(SimpleXMLElement)#308 (0) {

Possible problem origin:
You can test individual sites that you've enabled by going to http://127.0.0.1:*port*/post/similar?services=*serviceaddress* ,i.e. http://127.0.0.1:9000/post/similar?services=danbooru.donmai.us .By default,job_tasks and the external search from a post's page uses http://127.0.0.1:*port*/post/similar?services=all ,which returns the results from all sites you have enabled,which means if any of them returns an error,you won't get any result.

As far as I could tell,danbooru.donmai.us,yande.re,konachan.com,gelbooru.com and zerochan.net work well with all possible images (I haven't tested Haruhi doujins,Sankaku Channel,The Anime Gallery,Manga Drawing or Anime-Pictures). The issue stems from e-shuushuu.net - searching it for similar images will return the error. This problem is consistent with specific images(and does not exist for others). Manually taking said image to iqdb and searching for it only on e-shuushuu.net DOES return a result (http://e-shuushuu.net/image/153119/ for the reference image - 95% similarity).

(partial) Solution:
Go into config/config.php and search for the "public $image_service_list" section(no quotes). Delete the e-shuushuu entry. If tasks are used,go into http://127.0.0.1:*port*/phpmyadmin/ ,find the myimouto database and then the job_tasks entry: the status of external_data_search should be pending (and not processing,change it if you need to).

The downside to this solution is that it doesn't actually solve anything - I'm not sure what causes the problem or how to actually fix it. I suspect that the common ground between the images with this issue is that only pictures that don't return any results from e-shuushuu work,and images that do have similar counterparts on e-shuushuu will cause the error,but I didn't extensively test this.

System: 
Running win7 professional,Git 2.6.2-64-bit,Xampp win32-5.5.19-0-VC11,composer v1.0-dev. myimouto cloned when the latest commit was https://github.com/myimouto/myimouto/commit/49eff9539935d49b8690cdf16e3f61ae0ec7e37f .

**Comment by Parziphal** [comment]
I just changed the `image_service_list` to this:

```php
    public $image_service_list = [
        "danbooru.donmai.us" => "http://iqdb.org/index.xml",
        "yande.re"           => "http://iqdb.org/index.xml",
        "konachan.com"       => "http://iqdb.org/index.xml"
    ];
```

And it worked again. It looks like the domain was changed (it was `http://iqdb.yande.re/index.xml`).
