### ISSUE TITLE
Inline images?

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#163]
My inline images page is behaving weirdly. Accessing it gives me a plain white page with a table and a link to the first inline image "(no images)". I tried editing it and the functionality seems to work. I can upload and the pictures show up in the forum and comments, but not the wiki.

The main issue is that I can't create more. There is no "Create" link at the bottom of the page like in Moebooru. My first thought was a permissions problem but the edit page works and looks fine... Any ideas?

**Comment by Ma-ryan** [comment]
Okay, looks like I can create more entries by editing the MySQL database. That's hardly a solution though, and the new entry still won't show up at the inline images page. I can only access it by typing the id in the address bar.

Attached a screenshot in case no one has any idea what I'm talking about. lol

It looks as if something is failing to load. I suspect the solution may be simple and I'm overlooking something.
![screenshot - 280116 - 23 32 15](https://cloud.githubusercontent.com/assets/10130154/12658066/d4e5e018-c617-11e5-845b-5daa39235ce1.png)

**Comment by Parziphal** [comment]
Please check the logs (`log/development.log` or `production.log`). It's also probably that the error is shown in the page source (press `Ctrl+U` to view it).

**Comment by Ma-ryan** [comment]
There doesn't seem to be anything unusual in the page source (besides the lack of code). Here it is if you want to see it.

http://pastebin.com/DBS5XJCH

And this is about the only thing I can find about it in the logs. I don't know what to make of it. Does it make sense to you?

http://pastebin.com/rMTh6FQZ

**Comment by Parziphal** [comment]
<sub>_Inline images seem to be working fine..._</sub>
