### ISSUE TITLE
array_shift() expects parameter 1 to be array, boolean given

### ISSUE THREAD

**Issue by Shadoukun** [myimouto/myimouto#164]
Would really like a fix for this error with the batch uploading. Especially since you supposedly fixed it in #131 prior to your hiatus...like a year ago

>`PHP Warning
array_shift() expects parameter 1 to be array, boolean given
#0 [internal function]: Rails::errorHandler(2, 'array_shift() e...', '/home/shadou...', 12, Array)
#1 Rails/ActiveRecord/Adapter/MySql/QueryBuilder.php(12): array_shift(false)
#2 Rails/ActiveRecord/Adapter/AbstractQueryBuilder.php(30): Rails\ActiveRecord\Adapter\MySql\QueryBuilder->ca                  lculate_found_rows()
#3 Rails/ActiveRecord/Relation/AbstractRelation.php(552): Rails\ActiveRecord\Adapter\AbstractQueryBuilder->ex                  ecuteSql()
#4 Rails/ActiveRecord/Relation/AbstractRelation.php(77): Rails\ActiveRecord\Relation\AbstractRelation->execut                  eSql()
#5 Rails/ActiveRecord/Relation/AbstractRelation.php(108): Rails\ActiveRecord\Relation\AbstractRelation->take(                  )
#6 app/controllers/BatchController.php(29): Rails\ActiveRecord\Relation\AbstractRelation->paginate(1, 25)
#7 Rails/ActionController/Base.php(268): BatchController->index()
#8 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('index')
#9 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#10 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#11 public/index.php(3): Rails\Application\Base::dispatchRequest()
#12 {main}
Error context:
array(1) {
  ["rows"]=>
  &bool(false)
}
1`

**Comment by Parziphal** [comment]
I don't know if you're still using this, but I just pushed a bunch of fixes to job tasks that should fix all bugs. Although I didn't get this error when batch uploading.
