### ISSUE TITLE
How do you use this system?

### ISSUE THREAD

**Issue by Parziphal** [myimouto/myimouto#165]
I know this isn't a forum but I'm wondering, how do you use this system? I mean, do you host tons of anime pron, or other stuff? Locally or publicly?

**Comment by gcscaglia** [comment]
I've discovered myimouto a few years ago, on the yande.re forums (or was it at konachan?), when I was looking for means to organize my anime wallpaper collection, which had gotten out of hand.

Since then, I'm the sole user of a myimouto instance on my local network, running on a fedora system, apache and mariadb (mysql drop-in). There are about 15k images on the site and the only notable performance issue I've found is at tag/mass-edit.

I've made a few scripts / jobs around the system, all focused on single user and fetching images and meta-data from other boorus like tag types, automatically downloading and importing favorites, etc. Currently the major downfall of the system to me is the lack of an API like other moebooru sites have, but I don't have the knowhow or time to implement it myself, so I've been automating things by replicating the sames requests the browser would make.

Parziphal, Thank you very much for this system. Even if it's no longer actively maintained, it's a great system nevertheless, at very least for my own use case.

**Comment by Parziphal** [comment]
Thanks for replying and for your words, they are very kind.

I think the system has an API? it responds JSON or XML? like `/posts.json`, or what do you mean?

I remembered that I have a blog for this system, so I wrote a [new post](http://pop-works.blogspot.com/2015/12/a-new-version-from-scratch.html), hoping to get some feedback. heh.

**Comment by xkomachi** [comment]
I've discovered it a few months ago when looking for software that can manage a library of images,and the ability to fetch tags from other sources alongside the fact that as a rather casual user the install guide is human readable made me decide this is what I want to try. So far,I've been using it only locally with a small number of images,trying to troubleshoot the small bugs as they appear. Once I get all the basic functionality(mainly auto tagging and batch upload) I want sorted out,I'd use it personally for managing a small collection of mostly images from booru sites(~1000 pictures/videos). If that all works nicely,I want to try and figure out how extensible some features are and how easy it is to implement new features (like adding more search engines,adding support for more file types,or automatically replacing the image with a strictly higher resolution if one is available), and if the results for these are positive as well,I'd like to try operating it online for a small,closed community. 

Big plans,but as I'm not familiar with the systems myimouto is built on,so far my progress is very slow. My greatest bane is the lack of documentation on any scale,aside from the things which were meant to be changed(such as the config files); A small guide of how the folder structure is built and what files are stored in each; What functionality each file implements; Documentation of individual functions,more descriptive names for variables and inline comments for the more non-trivial parts of the code that explain what is being done. Although most of the time the general idea of what is being done is pretty simple,some long,complicated functions exist and when some of the variables used don't have an easy to get string representation,the logic gets hard to understand without having to dive into other files in search of how the classes and other functions the long function is built on work. 
Heh,maybe I'm just a sucker for documentation.

As for the blog post: Post browse mode is definitely a neat feature,but it is in no way needed for what I use (or any common use of the project I can imagine,really). For design: I rather like the current design,and I don't feel like infinite scrolling really fits (I'm imagining something like the current design of ibsearch). As for urls and responses,I have no real preference,and am willing to work with whatever provided. I don't see any problem with the current pool system (and I'm not with any other pool systems,tbh). The only thing I'd like to see revised is deleting posts,there seem to be many bugs with it.

If you have any more questions,or I'm not clear enough on something,I'd be happy to answer.

**Comment by Parziphal** [comment]
I see. If you follow the story behind this project (maybe you did), some points will be clarified (like why there's no documentation). Long story short, I built this basically for fun and to learn PHP and programming in general.

Currently, this system is practically an exact copy of Moebooru (or more precisely, what Moebooru was more than a year ago), so if you don't find documentation, or anything else here, it's because it wasn't present in the original code. Likewise, if you knew Moebooru, you would know this system as well. As for the framework MyImouto relies on, it was built by myself when I was learning to program, that's why it is a spaghetti (you'd know right away if you checked it) and there's no documentation for it because I wasn't sure. I think most of the effort I put on was on the framework rather than in the booru itself, because I needed (for the purpose I was going after) it to fit the code (instead of the code fit the framework).

Time has passed and I've learned more. I'm still very fond of this project and everytime I see it, I want to build it again, but with a (much) better code. I want to see this project shine... oh yes.

**Comment by gcscaglia** [comment]
@Parziphal Shame on me, the system do have an API, tested it today. Strange, I remember trying the default moebooru API URLs to no avail previously. Perhaps on a older version. Or not.

Thank you, I'll probably rewrite some of my utilities to consume the API instead.

**Comment by xkomachi** [comment]
I only encountered an abandoned system,but if there's somewhere that details the buildup process of either systems from scratch,I'd be very interested to read it.

**Comment by Shadoukun** [comment]
I use it hopefully to fill a gap in some of the other 'booru' sites, in terms of content. (I can PM you if you really want to know) but kind of wanted to stay within things I knew well enough (php and SQL)

We aren't all the way off the ground yet, but I'm working at it diligently.

**Comment by Parziphal** [comment]
@Shadoukun You're working diligently on what?

**Comment by Shadoukun** [comment]
Making it work? lol. A few bugs, host issues, uploading images, tagging. batch uploading still doesn't work. etc etc

**Comment by Parziphal** [comment]
@Shadoukun MyImouto has all that? I thought it was more stable than that.

**Comment by Shadoukun** [comment]
It's pretty stable, but some of its issues are just seemingly simple but turn out to haunt me. I didn't write the code...its a port...just a lot of 'learning to navigate'.

It doesn't error check very well, and the logs are often unhelpful in determining the problem. The core features are really stable, hence why I picked it up, its just a lot of little shit.
