### ISSUE TITLE
500 Internal Server Error - Installation

### ISSUE THREAD

**Issue by taichibana** [myimouto/myimouto#167]
Hi!

I'm using CentOS whit VestaCP, so MySQL, apache, nginx... are already configured. 
Things I've done:

- Apache Installed

- PHP Installed

- MySQL Installed

- GIT Installed

- Composer Installed

- Download MyImouto like explained on wiki, all the content from "MyImouto" folder moved to path 
"/home/username/web/subdomain.domain.com/public_html/" and the original "MyImouto" deleted because is empty (that content is on the path previously mentioned).

- At "/home/username/web/subdomain.domain.com/public_html/" "composer install" (Successfull)

- PHP.ini and "/etc/my.cnf" edited, and server restarted OK

- I think that the problem that I've comes when editing httpd.conf file and nginx.conf.

   - httpd.conf (original - made by VestaCP) --> http://pastebin.com/35xtH8ru
   - nginx.conf (original - made by VestaCP) --> http://pastebin.com/JvVQqQ7C

- After edition:

   - httpd.conf (Edited) --> http://pastebin.com/tCSA8XpS
   - nginx.conf (Edited) --> http://pastebin.com/WWdQ9GCu

- then the data base was created trough VestaCP:
   localhost
   UserName_databasename 
   UserName_username

- edit config/database.yml --> http://pastebin.com/342rLE8A

- edit config/config.php --> http://pastebin.com/Yzne8uQN

- Finally php install.php -OK- no problem

when I enter subdomain.domain.com I don see nothing, and if i enter "subdomain.domain.com/public/" nothing, and if enter "subdomain.domain.com/public/index.php" 500 Internal Server Error.

I did something wrong??

if anyone could help me, I would appreciate it

**Comment by Parziphal** [comment]
I know I'm really late, but, you tried to go to `/public/index.php` which means that you didn't read the installation guide carefuly. Also you shouldn't be using both Apache and Nginx, use only one (Apache is easier to configure).

**Comment by taichibana** [comment]
But is there any way I can use them at he same time?

**Comment by Parziphal** [comment]
I think you can indeed use both, but you must configure them so they don't conflict with one another. Regarding your http.conf second edition, I don't know what you're trying to do, plus I'm "rusty" in Apache. Just follow the installation instructions carefuly and everything should work fine.

**Comment by taichibana** [comment]
If I enter "subdomain.domain.com/blacklisted-preview.png" I can see the picture without any trouble, but when entering "subdomain.domain.com" I continue getting 500.
How can be posible I can see static content and then I got problems with .php

**Comment by Parziphal** [comment]
The error you get is generated by Nginx or Apache?

**Comment by taichibana** [comment]
I did not found nothing on nginx log or httpd log
But I found this on php log: http://pastebin.com/2fAaFtKg

**Comment by Parziphal** [comment]
You have to give write permissions to the `/log` and `/public/data` directories.

**Comment by taichibana** [comment]
Finally seems to work!!
Thanks!

**Comment by Parziphal** [comment]
:)))
