### ISSUE TITLE
After installation, "An error has occurred."  

### ISSUE THREAD

**Issue by yuti** [myimouto/myimouto#168]
check log/production.log
=>

PHP Warning
mkdir(): Permission denied 
#0 [internal function]: Rails::errorHandler(2, 'mkdir(): Permis...', '.../m...', 79, Array)
#1 Rails/Cache/Store/FileStore/Entry.php(79): mkdir('.../m...', 511, true)
#2 Rails/Cache/Store/FileStore.php(27): Rails\Cache\Store\FileStore\Entry->write(Array)
#3 Rails/Cache/Cache.php(54): Rails\Cache\Store\FileStore->write('rails.models.Us...', Array, Array)
#4 Rails/Cache/Cache.php(86): Rails\Cache\Cache->write('rails.models.Us...', Array, Array)
#5 Rails/ActiveRecord/Base.php(693): Rails\Cache\Cache->fetch('rails.models.Us...', Object(Closure))
#6 Rails/ActiveRecord/Base.php(671): Rails\ActiveRecord\Base->allCallbacks()
#7 Rails/ActiveRecord/Base.php(622): Rails\ActiveRecord\Base->getCallbacks('save', 'before')
#8 Rails/ActiveRecord/Base.php(409): Rails\ActiveRecord\Base->runCallbacks('save', Object(Closure))
#9 Rails/ActiveRecord/Base.php(383): Rails\ActiveRecord\Base->save(Array)
#10 app/controllers/ApplicationController.php(93): Rails\ActiveRecord\Base->updateAttribute('last_logged_in_...', '2016-02-17 13:3...')
#11 Rails/ActionController/Base.php(464): ApplicationController->set_current_user()
#12 Rails/ActionController/Base.php(230): Rails\ActionController\Base->runFilters('before')
#13 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#14 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#15 public/index.php(3): Rails\Application\Base::dispatchRequest()
#16 {main}
Error context:
array(2) {
  ["val"]=>
  array(7) {
    ["before_validation_on_create"]=>
    array(1) {
      [0]=>
      string(11) "_can_signup"
    }
    ["before_create"]=>
    array(1) {
      [0]=>
      string(9) "_set_role"
    }
    ["before_save"]=>
    array(1) {
      [0]=>
      string(17) "_encrypt_password"
    }
    ["before_validation"]=>
    array(1) {
      [0]=>
      string(27) "_commit_secondary_languages"
    }
    ["after_save"]=>
    array(2) {
      [0]=>
      string(18) "_commit_blacklists"
      [1]=>
      string(18) "update_cached_name"
    }
    ["after_create"]=>
    array(2) {
      [0]=>
      string(29) "_set_default_blacklisted_tags"
      [1]=>
      string(16) "_increment_count"
    }
    ["after_destroy"]=>
    array(1) {
      [0]=>
      string(16) "_decrement_count"
    }
  }
  ["header"]=>
  string(0) ""
}

**Comment by Parziphal** [comment]
Make sure you have write permissions to the `tmp` directory.

**Comment by yuti** [comment]
Still shows the error screen.

**Comment by Parziphal** [comment]
What error now?

**Comment by yuti** [comment]
OH!
After restart apache, now it works.
thanks!

**Comment by Parziphal** [comment]
:)))
