### ISSUE TITLE
Is there a way to allow users to view but not post?

### ISSUE THREAD

**Issue by welovekah** [myimouto/myimouto#169]
I may be going about things incorrectly, but it seems like the lowest user priviledge level that can view full posts is also able to make posts.  Is there a way to set up a user access level that can view but not post?

**Comment by Parziphal** [comment]
The lowest level can upload images but their status is automatically set to "pending". To disallow a user level to completely create posts, for example the `member` level, you can change `PostController.php` around line 29:

```php
public function create()
{
    if (current_user()->is_member_or_lower()) {
        $this->respond_to_error("Only privileged users can create posts", '#error', array('status' => 403));
    }
```

They'll still be able to access the upload page though, but their files will be rejected.
