### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by w1nr4r** [myimouto/myimouto#170]
I'm using Ubuntu and Nginx

When I go to the directory and type php install.php I get the following error.
```

*** Symfony\Component\Yaml\Exception\ParseException in Rails\Yaml\Parser#read ***
Error while reading file /var/www/myimouto/config/database.yml:
Unable to parse in "/var/www/myimouto/config/database.yml" at line 1 (near "﻿# Copy this to "database.yml" and adjust the fields accordingly.").
#0 Rails/Yaml/Parser.php(12): Rails\Yaml\Parser->read()
#1 Rails/Application/Base.php(265): Rails\Yaml\Parser::readFile('/var/www/myimou...')
#2 Rails/Application/Base.php(106): Rails\Application\Base->_load_active_record()
#3 Rails/Application/Base.php(50): Rails\Application\Base->boot()
#4 config/boot.php(29): Rails\Application\Base::initialize()
#5 install.php(7): require('/var/www/myimou...')
#6 {main}
Error context:
```

Any helps appreciated ~

**Comment by Parziphal** [comment]
Try removing the first 2 lines, that have a leading #.

**Comment by w1nr4r** [comment]
Thanks for replying Now I get

`Fatal error: Namespace declaration statement has to be the very first statement in the script in /var/www/myimouto/config/config.php on line 2
`
This is the second line of my config.php

`Fatal error: Namespace declaration statement has to be the very first statement in the script in /var/www/myimouto/config/config.php on line 2
`

**Comment by Parziphal** [comment]
Make sure there are no spaces before the `<?php` tag. Have you uploaded the file to some server?

**Comment by w1nr4r** [comment]
Figured it out Filezilla was opening the file in Libreoffice which was corrupting the file somehow.  I edited in gedit and now I get

`====================
 MyImouto installer 
====================

Admin account
Please enter a name and password for the admin account.
Note: the password will be shown.
Account name: 
`

So hopefully everything will work now. Thanks

**Comment by Parziphal** [comment]
Yeah, that seemed to be the case, some kind of encoding problem.
