### ISSUE TITLE
After Installation "An error has occurred."

### ISSUE THREAD

**Issue by w1nr4r** [myimouto/myimouto#171]
So when I go to my servers IP instead of the homepage I get

errors.png (image shows)
An error has occurred.

```
/var/www/myimouto$ sudo tail /var/log/nginx/error.log
#6 [internal function]: Rails::exceptionHandler(Object(Rails\Exception\PHPError\W" while reading response header from upstream, client: xx.xx.xxx.xx, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xx.xx.xx.xx"
2016/05/01 02:43:57 [error] 9586#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'fopen(/var/www/myimouto/log/production.log): failed to open stream: Permission denied' in /var/www/myimouto/vendor/zendframework/zend-log/src/Writer/Stream.php:79
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(/var/www/...', '/var/www/myimou...', 79, Array)
#1 /var/www/myimouto/vendor/zendframework/zend-log/src/Writer/Stream.php(79): fopen('/var/www/myimou...', 'a', false)
#2 /var/www/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(448): Zend\Log\Writer\Stream->__construct('/var/www/myimou...')
#3 /var/www/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(155): Rails::defaultLogger()
#4 /var/www/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(304): Rails::log()
#5 /var/www/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(268): Rails::reportException(Object(Rails\Exception\PHPError\Warning))
#6 [internal function]: Rails::exceptionHandler(Object(Rails\Exception\PHPError\W" while reading response header from upstream, client: xx.xx.xxx.xx, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xx.xx.xx.xx"
```

This is what the production.log shows

`[01-May-2016 03:08:56 UTC] [xx.xx.xxx.xx] GET /
PHP Warning
mkdir(): Permission denied 
#0 [internal function]: Rails::errorHandler(2, 'mkdir(): Permis...', '/var/www/myimou...', 79, Array)
#1 Rails/Cache/Store/FileStore/Entry.php(79): mkdir('/var/www/myimou...', 511, true)
#2 Rails/Cache/Store/FileStore.php(27): Rails\Cache\Store\FileStore\Entry->write(0)
#3 Rails/Cache/Cache.php(54): Rails\Cache\Store\FileStore->write('post_count=v=0', 0, Array)
#4 Rails/Cache/Cache.php(86): Rails\Cache\Cache->write('post_count=v=0', 0, Array)
#5 app/models/Post/CountMethods.php(15): Rails\Cache\Cache->fetch(Array, Object(Closure))
#6 app/controllers/StaticController.php(14): Post::fast_count()
#7 Rails/ActionController/Base.php(268): StaticController->index()
#8 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('index')
#9 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#10 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#11 public/index.php(3): Rails\Application\Base::dispatchRequest()
#12 {main}
Error context:
array(2) {
  ["val"]=>
  int(0)
  ["header"]=>
  string(0) ""
}
`

Not sure how to fix this... Is it folder/file permissions?  Any help is appreciated.

**Comment by Parziphal** [comment]
Make sure you have writing permissions for the `log/`directory.

**Comment by w1nr4r** [comment]
I have the log at 777 permission so it does have write permission

`[01-May-2016 07:37:43 UTC] [76.64.182.83] GET /
PHP Warning
mkdir(): Permission denied 
#0 [internal function]: Rails::errorHandler(2, 'mkdir(): Permis...', '/var/www/myimou...', 79, Array)
#1 Rails/Cache/Store/FileStore/Entry.php(79): mkdir('/var/www/myimou...', 511, true)
#2 Rails/Cache/Store/FileStore.php(27): Rails\Cache\Store\FileStore\Entry->write(0)
#3 Rails/Cache/Cache.php(54): Rails\Cache\Store\FileStore->write('post_count=v=0', 0, Array)
#4 Rails/Cache/Cache.php(86): Rails\Cache\Cache->write('post_count=v=0', 0, Array)
#5 app/models/Post/CountMethods.php(15): Rails\Cache\Cache->fetch(Array, Object(Closure))
#6 app/controllers/StaticController.php(14): Post::fast_count()
#7 Rails/ActionController/Base.php(268): StaticController->index()
#8 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('index')
#9 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#10 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#11 public/index.php(3): Rails\Application\Base::dispatchRequest()
#12 {main}
Error context:
array(2) {
  ["val"]=>
  int(0)
  ["header"]=>
  string(0) ""
}`

This is what I get

**Comment by Parziphal** [comment]
It's still complaining about denied permissions, but now I think it's for the `tmp` directory.

**Comment by w1nr4r** [comment]
Hmm my tmp is at 777...

**Comment by Parziphal** [comment]
According to my experience, sometimes the server's user is different from the user that created the files. So even if the folder is set to 777, the server's user can't create a new file/folder inside because tmp's parent folder's permissions don't allow that. If that's the problem, add the server's user (usually www-data) to your user group.

**Comment by w1nr4r** [comment]
sudo chown -R www-data /var/www/myimouto has fixed the error has occured problem thanks!

 ![ookk](https://cloud.githubusercontent.com/assets/18732196/14944518/276492f0-0fe5-11e6-9b02-157fc444dff1.png)

But every other page gives me a 404

"That page does not exist.
Return to index"

**Comment by Parziphal** [comment]
You're using nginx aren't you? have you ported the rewrite rules from the .htaccess file?

**Comment by w1nr4r** [comment]
I haven't i'm not that familiar with doing it either.  Do you have an example nginx config I could use?

**Comment by Parziphal** [comment]
Give me a moment...

**Comment by w1nr4r** [comment]
Thank you !

**Comment by Parziphal** [comment]
Sorry for the delay. I think this should work:

```
server {
  # here you may have some config ...  

  rewrite ^/(?:data/)?(preview|sample|jpeg|image)/([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{28})(?:/.*?)?(\.[\w]+)$  /data/$1/$2/$3/$2$3$4$5 last;

  location / {
    try_files $uri index.php;
  }
}
```

You have to edit, by default, the default server file located at `/etc/nginx/sites-available/default`, then run `sudo service nginx reload`. I use nginx but very basicly, and I haven't used it with MyImouto so I haven't tested this.

**Comment by w1nr4r** [comment]
Managed to fix my nginx config so that I can access the whole site here's the code

`server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/myimouto/public;
    index index.php index.html index.htm;

    server_name localhost;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location ~* \.php$ {
     fastcgi_pass unix:/var/run/php5-fpm.sock;
     fastcgi_index index.php;
     fastcgi_split_path_info ^(.+\.php)(.*)$;
     include fastcgi_params;
     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
     fastcgi_param SCRIPT_NAME $fastcgi_script_name;
  }
}`

Your rewrite didn't work unfortunately  it won't let me reload/reboot if I enter it in my config.

**Comment by Parziphal** [comment]
That's because there's no rewrite rules.
Alright, I tested an installation with Nginx and this server configuration worked fine:

```
server {
        listen 3000 default_server;

        root /home/www/myimouto/public;

        rewrite "^/(?:data/)?(preview|sample|jpeg|image)/([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{28})(?:/.*?)?(\.[\w]+)$" /data/$1/$2/$3/$2$3$4$5 last;

        location / {
                try_files $uri /index.php$is_args$query_string;
        }

        location ~ \.php$ {
                # This part may be different according to your environment.
                include snippets/fastcgi-php.conf;
                fastcgi_pass 127.0.0.1:9000;
        }
}
```

I checked why it wasn't working, and turns out that I had to enclose the rewrite rule in double quotes because the closing curly brackets end the `server { }` directive (found solution [here](https://forum.ivorde.com/starting-nginx-directive-rewrite-is-not-terminated-by-t59.html)).

**Comment by w1nr4r** [comment]
Yup it works now.  Thanks for all the help.

**Comment by Parziphal** [comment]
You're welcome.
