### ISSUE TITLE
php config/boot.php Error

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#173]
```
[ErrNo 8192]: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
#0 [internal function]: Rails::errorHandler(8192, 'preg_replace():...', '/opt/lampp/htdo...', 324, Array)
#1 vendor/toopay/assetic-minifier/src/Minifier/Cssmin.php(324): preg_replace('/(text-shadow:...', 'strtolower('$1 ...', '@charset "___YU...')
#2 vendor/toopay/assetic-minifier/src/Minifier/Cssmin.php(137): Minifier\CSSmin->minify('@charset "___YU...', false)
#3 Rails/Assets/Assets.php(509): Minifier\CSSmin->run('@charset "UTF-8...')
#4 Rails/Assets/Assets.php(336): Rails\Assets\Assets->compressFile('@charset "UTF-8...', 'css')
#5 Rails/Assets/Assets.php(196): Rails\Assets\Assets->compileFile(Object(Rails\Assets\File))
#6 Rails/Console/ApplicationConsole.php(56): Rails\Assets\Assets->compileAll()
#7 Rails/Application/Base.php(53): Rails\Console\ApplicationConsole->run()
#8 config/boot.php(29): Rails\Application\Base::initialize()
#9 {main}
Error context:
```
Can't change the css ,-,

**Comment by Parziphal** [comment]
Can you please write the steps to get this error? I can't reproduce it.

**Comment by Kille250** [comment]
I just delete the public Assets folder and typed in the console: php config/boot.php assets
It have compiled successfully the JS files, but i got an error after it turned to compile the css assets. ,-,

And sorry btw for all the threates that i open. ,-,

**Comment by Parziphal** [comment]
Back when the project was actively maintained I had tons of issues and requests and it was really fun to help out and implement changes, so don't worry.

I'll look at this and I'll let you know when I fix it.

**Comment by Kille250** [comment]
Alright. Thanks!

**Comment by Kille250** [comment]
And? Do you have looked at this? :D

**Comment by Parziphal** [comment]
Actually what you need to do is just to change the CSSMin.php file noted in the log with this one: https://github.com/toopay/assetic-minifier/blob/master/src/Minifier/CSSMin.php

**Comment by Kille250** [comment]
Alright. It's working now! 
One question, do you know where i must put 
'''
Video{
...
}
'''
In which css. I have used the way from a guy to upload webm and mp4 and i want to set up the height+width. ,_,

**Comment by Parziphal** [comment]
Just place that inside any css file.

**Comment by Kille250** [comment]
Alright. Put it in every one. It works now. Thank you for your help. I love you! :D

**Comment by Kille250** [comment]
I need you one last time. /root/Desktop/myimouto-master/app/assets/javascripts/i18n
I want to add this piece of code: 
'''
var video = document.getElementById('video');
video.addEventListener('click',function(){
  video.play();
},false);
'''
Where should i put it in? ,-, I'm kindly a noob in js.

**Comment by Parziphal** [comment]
Also in any js file.

**Comment by Kille250** [comment]
at the end of the files?

**Comment by Parziphal** [comment]
This would be better:

```php
$(function() {
  var video = document.getElementById('video');
  video.addEventListener('click',function(){
    video.play();
  },false);
});
```

Place it wherever you want, but preferably at the end.

**Comment by Kille250** [comment]
Have done that. Isn't working. I don't know why. ,-,

**Comment by Parziphal** [comment]
Did you put the code inside `$(function() { .... });`? Try checking the JS console (`ctrl+shift+J` or F12 in Firefox) for errors.
You're not bothering! I told you not to worry.

**Comment by Kille250** [comment]
```
$(function() {
  var video = document.getElementById('video');
  video.addEventListener('click',function(){
    video.play();
  },false);
});
```
I put this at the end of a few js files. Under all the code. ,-,

**Comment by Parziphal** [comment]
Try checking the console in the browser for errors (`ctrl+shift+J` or F12 in Firefox).

**Comment by Kille250** [comment]
Wait, must insert the code again. :c

**Comment by Kille250** [comment]
http://p0rngramm.de/post/show/226/anime-remix-sfw-sound-video

There you can see it yourself. Some js are corrupted. The news message isn't showing up and the dropdown menu isn't working. ,-,

**Comment by Parziphal** [comment]
It seems like you're inserting the code before jQuery is loaded. You need to insert it after jQuery is fully loaded.

**Comment by Kille250** [comment]
How? xD

**Comment by Parziphal** [comment]
Try creating a file in `app/assets/javascripts` called "video.js" and insert that code there, then compile. That should work.

**Comment by Kille250** [comment]
only that?

**Comment by Parziphal** [comment]
Let's see if that works...

**Comment by Kille250** [comment]
ok wait

**Comment by Kille250** [comment]
Don't want to start the video. ,-,

**Comment by Parziphal** [comment]
For some reason the code was sent to the top of everything even though according to the `application.js` file it should have been included at the end in `require_tree .`, unless you've changed the file. Have you?

**Comment by Kille250** [comment]
After that yes. You can visit it now without the edited application.js.

**Comment by Parziphal** [comment]
Uuuh try changing the first line to `jQuery(function() {`?

**Comment by Kille250** [comment]
I love you

**Comment by Kille250** [comment]
one thing. I want to set up a poster to the video. How can i set it up to do it automatically? Because i want to add a mobile support. ,-, Android isn't showing anything because it don't want to preload the video.

**Comment by Parziphal** [comment]
You mean you want to create thumbnails/previews for the videos?

**Comment by Kille250** [comment]
No. If the video doesn't have started, you see something like a preview. For that you use normally a poster command `<video poster="..."`. I don't know how i can set it up that the player is taking the pictures from the created previews. ,-,

**Comment by Parziphal** [comment]
Hmmm I guess you have edited the post view somewhere in `app/views/post/show_partials`, to insert the video tags? Beucase I'd say there you can place the `poster` attribute like:

```html
<video poster="<?= $this->post->preview_url() ?>"> ...
```

**Comment by Kille250** [comment]
`$this->post->preview_url` this was what i missed. Used `$this->post->image` or something like that. Doesn't made sense. Alright. Thank you very much!

**Comment by Parziphal** [comment]
You're very welcome!
