### ISSUE TITLE
Question: Page Title

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#174]
How can i set up on every page the same page title. If i go to a post i see every time the tags.

**Comment by Parziphal** [comment]
If I'm not wrong, setting a hardcoded page title in `app/views/layouts/default.php` is what you want.

**Comment by Kille250** [comment]
Alright, thank you again for your help!

**Comment by Kille250** [comment]
One question again. How can i auto tag "nsfw" if the post has the rating=explicit. I have got it to work if the file is a webm/mp4 that it got automatically the tag "video". But i don't get it to work with the explicit rating. ,-,

**Comment by Kille250** [comment]
One question again. How can i auto tag "nsfw" if the post has the rating=explicit. I have got it to work if the file is a webm/mp4 that it got automatically the tag "video". But i don't get it to work with the explicit rating. ,-,

**Comment by Kille250** [comment]
`elseif ($post->rating == 'q' && CONFIG()->add_video_tag_to_rating)
            $this->new_tags[] = 'nsfw';`

What have i done wrong?

**Comment by Parziphal** [comment]
I think the only way to add tags upon creation would be by editing the `before_creation()` method in `app/models/Post.php`.  The following will add `nsfw` tag to "rating e" pics:

```php
if ($this->rating == 'e') {
    $this->new_tags[] = 'nsfw';
}
```

But isn't tagging as "nsfw" a "rating e" picture redundant? As rating e are already nsfw.

Now what is wrong with your line of code is that `()` after the `'q'`; it should work after removing those parenthesis:

```php
elseif ($post->rating == 'q' && CONFIG()->add_video_tag_to_rating) {
    $this->new_tags[] = 'nsfw';
}
```

**Comment by Kille250** [comment]
omg. I'm so dumb. thank you.. ,_,
