### ISSUE TITLE
WARNING: Error on database query execution

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#175]
http://localhost:3000 reports the following:

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> Apache/2.4.7 (Ubuntu) Server at localhost Port 3000

/var/www/myimouto/log/production.log reports the following:

> WARNING: Error on database query execution
> [SQLSTATE 23000] (1452) Cannot add or update a child row: a foreign key constraint fails (`myimouto`.`user_blacklisted_tags`, CONSTRAINT `fk_user_bl_tags__user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)
> 

According to http://stackoverflow.com/questions/5005388/cannot-add-or-update-a-child-row-a-foreign-key-constraint-fails, this is the reason why I keep getting this error, but I don't really know how to fix this...:

> You're getting this error because you're trying to add/update a row to table2 that does not have a valid value for the UserID field based on the values currently stored in table1.

**Comment by Parziphal** [comment]
Is this a fresh installation? If it is, did you follow the installation steps carefuly?

**Comment by Justawinterwolf2012** [comment]
I followed the steps that I could on my Ubuntu machine (yes, I know that
the steps were designed for XAMPP on Windows), and it appears the
installation was successful, but I'm having this only problem. This was a
clean install of  phpMyAdmin, MySQL, Apache2, and php5.

**Comment by Parziphal** [comment]
Can you show the complete log info of that error?

**Comment by Justawinterwolf2012** [comment]
The only log info I can find is under /var/www/myimouto/log/production.log, and reads as such:

> `WARNING: Error on database query execution
[SQLSTATE 23000] (1452) Cannot add or update a child row: a foreign key constraint fails (`myimouto`.`user_blacklisted_tags`, CONSTRAINT `fk_user_bl_tags__user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)`

**Comment by Parziphal** [comment]
There's nothing else? No date/time, no backtrace? _wat_

It seems like this error was logged when you ran the installer, right?

**Comment by Justawinterwolf2012** [comment]
I'm guessing so... I ran `php install.php` set the username and password of the admin account, visited localhost:3000, and was greeted by that... I'm sorry I can't provide anything more...
![screenshot - 07102016 - 06 55 48 pm](https://cloud.githubusercontent.com/assets/16302135/16717864/f43ea3bc-46cf-11e6-88a5-d86ca9e19b0c.png)

**Comment by Parziphal** [comment]
Alright... I think that logged error has nothing to do with the white page you see when you go to your site. Can you check if there's any record in the `users` table?

**Comment by Justawinterwolf2012** [comment]
Here's a dump of my Users database
[https://1drv.ms/u/s!ArKnFSaXTkyhom99REd5EQz_mnro](url)

**Comment by Parziphal** [comment]
I find strange that the id of this user is 2, it should be 1.

Ok, regarding the logged error, it seems like that the installer failed to create the admin user, therefore the following query, which tries to create the blacklist for that user, failed because it referenced a user record that doesn't exist. It seems like you ran the installer twice, but definitely something went wrong. Why would the admin user failed to be created? I really don't know.

Now, since you say that `it appears the installation was successful` (and like I said before), that logged error has nothing to with the error page you see (it only means "there was an error with creating the admin user"). That `Internal Server Error` page shows because of some missconfiguration, or because of missing modules. For example, make sure you have the `rewrite` mod installed and enabled.

So... solution would be to check your Apache configuration and your environment.

**Comment by Parziphal** [comment]
I wrote a guide on how to install MyImouto on Ubuntu. Perhaps it may help: https://github.com/myimouto/myimouto/wiki/How-to-install-on-Ubuntu

**Comment by Justawinterwolf2012** [comment]
I read your guide, and for the most part it worked, but when you said to type `php installer.php`, you probably meant `php install.php`. Also, when you said to `cp config/config.php.example config/config.php` and `cp config/database.yml.example config/database.yml`, you should have had us `cd` back into the directory where we cloned MyImouto so we can change config and so on.

**Comment by Parziphal** [comment]
Oh, that `installer.php` was a typo indeed, thanks. About the `cp` I don't understand what you mean... following the guide, when you clone the repo and go inside the folder, you stay there as there's no other command to change dir, so `cp config/config.php.example config/config.php` works just fine and you're still inside the `myimouto` dir.

Anyway, is it working now?

**Comment by Justawinterwolf2012** [comment]
It's working great! I mean, since I usually visit Danbooru imageboards a lot, there are some things I need to learn about, but it's almost exactly the same!

There are just two things I cant figure out for the life of me:
1. I want to change the link that "Wiki" (in the top bar) links to ([http://localhost:3000/wiki/show?title=help%3Ahome](url) to [http://localhost:3000/wiki](url)), but I can't seem to find anything... How would I do that?
2. How would I go about changing the header image and background color?

**Comment by Justawinterwolf2012** [comment]
And you were right about the `cd` thing. I wanted to use Thunar and gedit to open the files under a root environment, so I did `cd /var/www/myimouto/` then the commands.

**Comment by Parziphal** [comment]
Good to know it's working. You can make the wiki link to link to the index by setting `$menu_wiki_link` to `null` in your config file.

This system is a clone (more exactly a port) of [Moebooru](https://github.com/moebooru/moebooru), which is a [Danbooru](https://github.com/r888888888/danbooru) 1 fork... so Moebooru (and therefore, MyImouto) looked very alike Danbooru, but Danbooru changed to version 2 some years ago and changed a little more, while Moebooru (and therefore MyImouto) kept the old look.

To learn more about what you can do with the system (options, configs), have a look at the [About MyImouto](https://github.com/myimouto/myimouto/wiki/About-MyImouto) wiki to know about features, and read the `config/default_config.php` file for more features not listed in the wiki. And if you need help again, just create another issue.
