### ISSUE TITLE
ERROR: Couldn't retrieve new primary key

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#179]
So I got everything up and going, but it's not working all the way.
After uploading a picture with tags, the tags don't show up, and after trying to create a wiki post, an error message says "ERROR: Couldn't retrieve new primary key". I have a feeling it has to do something with MySQL, but I don't definitively know... I hate to sound noobish, but help?

**Comment by Parziphal** [comment]
_woops_

**Comment by Parziphal** [comment]
What version is your MySQL?

**Comment by Justawinterwolf2012** [comment]
Well, it's a funny story, but I wiped my Lubuntu 14.04 installation and replaced it with 16.04, so I'll try it again and report back... sorry...

**Comment by Parziphal** [comment]
I got the same error with MySQL 5.7. If you want to use 5.7, make sure to disable `innodb_strict_mode`, and `sql_mode` must not include `STRICT_TRANS_TABLES`.

**Comment by Justawinterwolf2012** [comment]
So how would I go about disabling/un-including these? Would they be in the my.conf file?

**Comment by Justawinterwolf2012** [comment]
Because now I'm getting the issue of the favicon showing up in the tab, but the page is completely white...

**Comment by Parziphal** [comment]
Yes, you'd have to add this to my.conf:

```
innodb_strict_mode = OFF
sql_mode = "ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

That list is the default sql_mode except that strict trans tables was removed.

**Comment by Parziphal** [comment]
About the white page, please check the log file.

**Comment by Justawinterwolf2012** [comment]
I found nothing in the log files for MyImouto, but when I was looking through the MySQL logs, it looks like it wasn't using a password to access the database during the initialization (even though I set it in database.yml)  and MySQL was throwing all kinds of errors. Should I try dumping the myimouto database and tables, then try the install.php script again?

**Comment by Parziphal** [comment]
Yes, why not.

**Comment by Justawinterwolf2012** [comment]
I'm still getting nothing but a blank screen... Just to test if my configuration was bad, I trying flipping the original port 80 VirtualHost to 3000, and vise versa for the MyImouto VirtualHost, but still no cigar.

After checking the MyImouto database, it looks like all the tables populated correctly, but still no results.

**Comment by Parziphal** [comment]
Have you given permissions to `tmp` and `public/data` folders? Have you checked PHP and Apache logs? Is PHP configured to output errors?

**Comment by Justawinterwolf2012** [comment]
I followed the last instructions in the guide you made in regards to the file permissions, I cant seem to find apache's and php's logs in /var/logs, and `display_errors = On`

**Comment by Parziphal** [comment]
Try /var/logs/upstart/
Also try setting this in index.php:

```php
<?php
phpinfo(); exit;
```

Does that output anything? It should.

**Comment by Justawinterwolf2012** [comment]
I don't know how many times I said "It must be Ubuntu xx.04, let's just wipe the SSD and go back to Ubuntu xx.04", but this time it worked when I went back to 14.04. Everything worked without a hitch, and I'm internally raging.

Thank you for your help!
