### ISSUE TITLE
How to add tag types?

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#180]
Okay, now that I got this installation problem out of the way, I started uploading my collection of art into it, and it works great! It's just like the Imageboard I pulled them from.

So after uploading a few pictures into it, I noticed that there only a few tag types I can categorize them into, and I was wondering if there was some GUI tool that I can use to create more?

**Comment by Parziphal** [comment]
There's no GUI, you'll have to edit files. Here's how:

Let's say we want to create a tag type called `game`.

Edit `config/config.php` and add this inside the `LocalConfig` class:

```php
class LocalConfig extends DefaultConfig
{

    // ....etc

    public function __construct() {
        $this->tag_types = array_merge($this->tag_types, [
            "Game"      => 7,
            "game"      => 7,
            "gemo"      => 7
        ]);
    }
}
```

We're adding an array of `tag_name => id` to the `tag_types` array. The first element ("Game") is the name of the new tag. The second element ("game", lower case) will allow us to set types when tagging posts (more on this below) , and the third element is an alias.

That's it. Now you can create tags of type game. You can go to your tag index, and under the Type dropdown you'll see "Game".

Remember that you can also set types to tag upon editing a post. Tagging a post like either `game:radiant_silvergun` or `gemo:radiant_silvergun` will create the "radiant_silvergun" tag if it doesn't exist, and will set its type to "game". `Game:radiant_silvergun` won't work.

Now you'd like to set a special color for that new tag type. Let's set the color to something purple. Open `app/assets/stylesheets/my_imouto.css.scss` and add this:

```css
.tag-type-game>a,
#history .tag-type-game,
.color-tag-types .tag-type-game {
  color: orchid;
}
```

Each tag type need these 3 CSS rules to set colors in different pages of the site.

Now we need to recompile the assets by running this command:

    php config/boot.php assets compile:application.css

Now you're done. Refresh your site and you should now see your new tag with the new color.

**Comment by Justawinterwolf2012** [comment]
And lastly, before I close the issue, how would I get this to show at the top of the tags list with {{character:*}} and {{artist:*}} tags?

**Comment by Parziphal** [comment]
Change the `$tag_order` property in your config:

```php
class LocalConfig extends DefaultConfig
{
    // ...etc
    
    public $tag_order = [
        'game',
        'circle',
        'artist',
        'copyright',
        'character',
        'general'
    ];
}
```

As you can read in the `default_config.php` file, that property is used to _Tag type ordering in various locations_.

**Comment by Justawinterwolf2012** [comment]
Crap, sorry... I must've scrolled past it... Well, thank you for all your help!

**Comment by Justawinterwolf2012** [comment]
I'm having a problem assigning a color to the tag category, and no matter what I've tried, I can't fix it. I got the tag category to work just fine, but when running the command to recompile the CSS file, it throws this error:
`jonathin@tux-linux:~/myimouto$ php config/boot.php assets compile:application.css
Compiling file /home/jonathin/myimouto/app/assets/stylesheets/application.css
*** PHP Warning ***
preg_match(): Compilation failed: invalid range in character class at offset 45 
#0 [internal function]: Rails::errorHandler(2, 'preg_match(): C...', 'Rails/Assets/Pa...', 119, Array)
#1 Rails/Assets/Parser/Base.php(119): preg_match('~^\\W+=\\s+?(requ...', '/*', NULL)
#2 Rails/Assets/Parser/Base.php(59): Rails\Assets\Parser\Base->extractDirectives()
#3 Rails/Assets/Assets.php(332): Rails\Assets\Parser\Base->parse(3)
#4 Rails/Console/ApplicationConsole.php(65): Rails\Assets\Assets->compileFile('application.css')
#5 Rails/Application/Base.php(53): Rails\Console\ApplicationConsole->run()
#6 config/boot.php(29): Rails\Application\Base::initialize()
#7 {main}
Error context:

`

I know I'm doing something wrong... But I can't seem to figure out what. Here's what I put in `app/assets/stylesheets/my_imouto.css.scss`:

`.tag-type-species>a,
#history .tag-type-species,
.color-tag-types .tag-type-species {
  color: orchid;
}
.tag-type-species>a:hover{
  color:#33cfff
}`

**Comment by Parziphal** [comment]
Actually you're not doing something wrong, it's the framework that is causing this error. But I can't reproduce this in PHP 5.6 nor PHP 7.01. What PHP version are you using?

**Comment by Justawinterwolf2012** [comment]
I am using PHP 7.0.9-1+deb.sury.org~trusty+1

**Comment by Parziphal** [comment]
I made a modification which should fix this error. Update the framework by running `composer update`, the framework should update to version `1.0.3`.

**Comment by Justawinterwolf2012** [comment]
Happy to report that worked! Thank you!
