### ISSUE TITLE
How to hide artist and pool from navbar?

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#181]
How would I hide `<li class="artist">` (highlighted in yellow) and `<li class="comment">` (highlighted in blue) from `<div class="clearfix" id="main-menu" data-controller="post">` in all pages? I find those options obsolete for what I'm trying to achieve with my local imageboard, being that I'm not broadcasting it to the world. I usually just tag the artist with `{{artist:xyz}}`, and I wouldn't leave a comment for myself... unless I'm just lonely.

![untitled](https://cloud.githubusercontent.com/assets/16302135/16898571/25badc22-4b93-11e6-8bb4-7d0256e6f1ba.png)

**Comment by Parziphal** [comment]
Open `app/assets/stylesheets/my_imouto.css.scss` and add these lines:

```scss
#main-menu {
  li.artist, li.comment {
    display: none;
  }
}
```

Then recompile assets by running `php config/boot.php assets compile:application.css`, then refresh your browser.

**Comment by Justawinterwolf2012** [comment]
Perfect, thank you!
