### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Raven1196** [myimouto/myimouto#183]
First, great job!

Second: How could change the language dynamically according to browser accepts using locales/?

Using:
`substr($_SERVER["HTTP_ACCEPT_LANGUAGE"],0,2)` returns en/es/de/ru/etc

 by example.  What I need add or modify?

I know nothing of Rails and I end up getting dizzy.

Thank you.

**Comment by Parziphal** [comment]
About first, thanks~

About second, the language is set in `app/controllers/ApplicationController.php` on line `355`, method `set_locale`. For your needs, the method would look like this:

```php
protected function set_locale()
{
    $locale = null;
    
    if ($this->params()->locale) {
        $locale = $this->params()->locale;
    } elseif ($this->cookies()->locale) {
        $locale = $this->cookies()->locale;
    } elseif (isset($_SERVER["HTTP_ACCEPT_LANGUAGE"])) {
        $locale = substr($_SERVER["HTTP_ACCEPT_LANGUAGE"], 0, 2);
    }

    if ($locale and in_array($locale, CONFIG()->available_locales)) {
        $this->I18n()->setLocale($locale);

        if ($this->params()->locale) {
            $this->cookies()->locale = [ 'value' => $this->params()->locale, 'expires' => '+1 year' ];
        }
    } else {
        $this->I18n()->setLocale(CONFIG()->default_locale);
    }
}
```

You could consider a more robust way to get the correct requesting language, which would be by using this library: https://github.com/willdurand/Negotiation

**Comment by Raven1196** [comment]
Thank you for answering so quickly.
The code works partially.

With "es" browser:
http://puu.sh/qeggp/0bf8414dca.png
http://puu.sh/qeg5r/01459deeff.png
thats works great!

But entire "main-menu" of "layouts/_menu.php" isn't translated.
http://puu.sh/qefDj/7e9c3564c9.png

I see yml files correct.

**en.yml**
> 
    menu:
      account:
        _: My Account
        change_password: Change Password
        favorites: My Favorites
        login: Login
        logout: Logout
        mail: My Mail
        profile: My Profile
        reset: Reset Password
        settings: Settings
      artists:
        _: Artists
        create: Create
        search: Search Artists
        view: View Artists
      comments:
        _: Comments
        moderate: Moderate
        search: Search Comments
        view: View Comments
      forum:
        _: Forum
        mark_all_read: Mark All Read
        new: New Topic
        search: Search Forums
        view: View Topics
      help:
        _: Help
        artists: Artist Help
        comments: Comment Help
        forum: Forum Help
        notes: Note Help
        pools: Pool Help
        posts: Post Help
        site: Site Help
        tags: Tag Help
        wiki: Wiki Help
      more: More »
      new_mail: New Mail
      notes:
        _: Notes
        requests: Requests
        search: Search Notes
        view: View Notes
      pools:
        _: Pools
        create: Create New Pool
        search: Search Pools
        view: View Pools
      posts:
        _: Posts
        batch: Batch Upload
        history: History
        image_search: Image Search
        moderate: Moderate
        popular: Popular
        random: Random
        search: Search Posts
        upload: Upload
        view: View Posts
      tags:
        _: Tags
        aliases: Aliases
        edit: Edit
        implications: Implications
        mass_edit: Mass Edit
        popular: Popular
        search: Search Tags
        view: View Tags
      wiki:
        _: Wiki
        create: Create New Page
        index: View Wiki Index
        search: Search Wiki

**es.yml**
>      menu:
      account:
        _: Mi Cuenta
        change_password: Cambiar contraseña
        favorites: Mis Favoritos
        login: Identificarse
        logout: Desconectarse
        mail: Mi correo
        profile: Mi perfil
        reset: Restaurar contraseña
        settings: Configuración
      artists:
        _: Artistas
        create: Crear
        search: Buscar artistas
        view: Ver artistas
      comments:
        _: Comentarios
        moderate: Moderar
        search: Buscar comentarios
        view: Ver comentarios
      forum:
        _: Foro
        mark_all_read: Marcar todos como leídos
        new: Nuevo tema
        search: Buscar en los foros
        view: Ver temas
      help:
        _: Ayuda
        artist: Ayuda en Artistas
        comment: Ayuda de Comentarios
        forum: Ayuda de Foros
        note: Ayuda en Notas
        pool: Ayuda en Álbumes
        post: Ayuda de Posts
        site: Ayuda del sitio
        tag: Ayuda de Etiquetas
        wiki: Ayuda de la Wiki
      more: Más »
      new_mail: Mensaje nuevo
      notes:
        _: Notas
        requests: Peticiones
        search: Buscar notas
        view: Ver notas
      pools:
        _: Álbumes
        create: Crear nuevo álbum
        search: Buscar álbumes
        view: Ver álbumes
      posts:
        _: Posts
        batch: Subida en lote
        history: Historia
        image_search: Buscar imagen
        moderate: Moderar
        popular: Populares
        random: Aleatorio
        search: Buscar Posts
        upload: Subir
        view: Ver Posts
      tags:
        _: Etiquetas
        aliases: Alias
        edit: Editar
        implications: Implicaciones
        mass_edit: Edición en masa
        popular: Populares
        search: Buscar Etiquetas
        view: Ver Etiquetas
      wiki:
        _: Wiki
        create: Crear nueva página
        index: Ver Índice de la Wiki
        search: Buscar en la Wiki

**Comment by Parziphal** [comment]
Well that looks like a bug, because it happens even if you simply pass `?locale=es`. IIRC, the menu HTML is cached, and it seems like the cache is not deleted when the user requests a different language.
But I just tested and the menu is still in english even if I load a page in incognito with `?locale=es`. So yes, that's a bug.

**Comment by Raven1196** [comment]
With fresh install its the same.
http://puu.sh/qeFsH/eb87fd5850.png

:(

**Comment by Parziphal** [comment]
Yes, it's a bug, the system shouldn't behave like that, I have to fix it.
It seems like not many people change language because nobody has reported this so far.

**Comment by Raven1196** [comment]
In _menu.php
If prints directly:
`<?= $this->t('.account._') ?>`
shows in request's langauge.

But all with "linkTo":
`<?= $this->linkTo($this->t('...'), ....) ?>`
it doesn't.

**Comment by Parziphal** [comment]
This error happened because the system was caching one version of the menu, in one language. So even if the language was changed by the user, the system would check for the cached menu, which would be in the previous language, and use that.

Now the menu is cached in every available language.
