### ISSUE TITLE
Problem with Post-data

### ISSUE THREAD

**Issue by Raven1196** [myimouto/myimouto#184]
It's me again. :(

There was a problem with some "POST" with locale=es, by example.

In app/views/artists/destroy.php in line 5:

```
  <?= $this->submitTag($this->t('buttons._yes')) ?>
  <?= $this->submitTag($this->t('buttons._no')) ?>
```

In ArtistController.php in line 25:

```
    public function destroy()
    {
        $this->artist = Artist::find($this->params()->id);

         if ($this->request()->isPost()) {
             if ($this->params()->commit == "Yes") {
                $this->artist->destroy();
                $this->respond_to_success("Artist deleted", ['#index', 'page' => $this->page_number()]);
            } else {
                $this->redirectTo(['#index', 'page' => $this->page_number()]);
            }
        }
    }
```

Commit is comppared with "Yes" always, not its equivalent in locale's  language.

Same problem in:
app\controllers\DmailController.php <-> app\views\dmail\confirm_mark_all_read.php

**Comment by Parziphal** [comment]
I'll have to fix that too.

**Comment by Parziphal** [comment]
The problem in Dmail was that the footer link to mark all as read, sent a POST request without any additional parameter, so actually the user could never mark all their dmails as read.

Thanks for the reports.
