### ISSUE TITLE
exclude_tags in config breaks job tasks

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#185]
I tried setting some tags to exclude them from the external data search, but doing so completely breaks the job task script from running.

For example, I put the child tag like so: ```'exclude_tags' => [child],``` and after I run job tasks I get this error from the terminal:

```# php /home/booru/myimouto/script/daemons/job_task_processor.php
*** PHP Notice in MyImouto\Application#init ***
Use of undefined constant child - assumed 'child' 
#0 config/application.php(18): Rails::errorHandler(8, 'Use of undefine...', '/home/booru...', 18, Array)
#1 Rails/Application/Base.php(109): MyImouto\Application->init()
#2 Rails/Application/Base.php(50): Rails\Application\Base->boot()
#3 config/boot.php(29): Rails\Application\Base::initialize()
#4 script/daemons/job_task_processor.php(3): require('/home/booru...')
#5 {main}
Error context:```

And from the log:

```PHP Notice:  Use of undefined constant child - assumed 'child' in /home/booru/myimouto/config/application.php on line 18```

**Comment by Parziphal** [comment]
I think you mean `'exclude_tags' => ['child']`? As the error notes, `child`, without quotes, is a constant, which of course is not defined.

**Comment by Ma-ryan** [comment]
You're right lol. It works fine with the quotes. My mistake. The config example had no quotes, though. Probably should be added.

**Comment by Parziphal** [comment]
Oh. In which file is the example without quotes? `default_config.php` doesn't have any example: https://github.com/myimouto/myimouto/blob/master/config/default_config.php#L436.

**Comment by Ma-ryan** [comment]
I forgot about this issue, sorry.

I meant to say that the config option doesn't have empty quotes, or anything in the comment about them. I was confused initially how to separate tags too. Took a bit of trial and error, but I got it to work.
