### ISSUE TITLE
[HALP!] Updating MyImouto

### ISSUE THREAD

**Issue by Vanndril** [myimouto/myimouto#186]
Wow, am I excited to see all the updates all of a sudden within the last week!

But I'm feeling mighty dumb right now. I could have sworn there was a command I could run via SSH that would update the MyImouto files on our server. However, I can't recall what it is. I think it may have used Git, but I don't remember very clearly.

I know this is a very random request, but could you kindly remind me if there was a command for that? XD

**Comment by Parziphal** [comment]
Long time no see! How have you been?
You mean git pull?

**Comment by Vanndril** [comment]
Yes, yes it has! I've been good. The site has kept me quite busy. :P

Did you decide to revive MyImouto, or is this a temporary return just to clean things up a bit? :3
_________________________

I believe that might be the one, yes. So, running:

git pull https://github.com/myimouto/myimouto.git

should update the files on the FTP server with the ones from this repository, correct?

Sorry for making you hold my hand though this. To be honest, I'm terrible at using command lines for stuff. :P

**Comment by Parziphal** [comment]
I think you only need to run "git pull" inside the system folder.

I'm just fixing bugs to leave the project in a stable state.

**Comment by Vanndril** [comment]
Yep, that was the one! Thank ye!

And thanks for stabilizing the project. Hope to see you around somewhere after this project retires.
