### ISSUE TITLE
[Bug] Can't import images

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#187]
I can not get the import function to work. I put some files in /home/sequesnzia/myimouto/public/data/import/pixiv cate2/ and when i click the import link i get the following error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Rails::reportException() must be an instance of Exception, instance of Error given, called in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 268 and defined in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php:295
Stack trace:
#0 /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(268): Rails::reportException(Object(Error))
#1 [internal function]: Rails::exceptionHandler(Object(Error))
#2 {main} thrown in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 295
```

Latest Ubuntu 14.04 with latest pull (did it today)

I have tired multiple sub folders and no sub folders with no result. I have tried it being owned by my user, root, and www-data and some result aswell.

**Comment by Parziphal** [comment]
It looks like the exception handling changed a little in PHP 7.0. I'll check on that.

**Comment by Parziphal** [comment]
Can you try this? Open the `composer.json` file and change this line:

    "railsphp/railsphp": "1.0.*",

for this:

    "railsphp/railsphp": "dev-master",

Then run `composer update`. It must update the files (it must not say something like "Nothing to update."). After the files are updated, try reproducing the error again,

**Comment by UiharuKazari2008** [comment]
Did that and same result of:
`Fatal error: Uncaught TypeError: Argument 1 passed to Rails::reportException() must be an instance of Exception, instance of Error given, called in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 268 and defined in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php:295 Stack trace: #0 /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(268): Rails::reportException(Object(Error)) #1 [internal function]: Rails::exceptionHandler(Object(Error)) #2 {main} thrown in /home/seque/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 295`

I also tried deleting my installation, dropping the db, and installing from scratch via the wiki and same result. I also noticed that its not displaying sample images correctly. I would have to click show larger version every time.
I would prefer installing this on Debian but i try to use what ever works for this.

**Comment by UiharuKazari2008** [comment]
![capture695](https://cloud.githubusercontent.com/assets/15165770/17410461/c85a1832-5a41-11e6-8a2d-094900e58ee1.png)
Here are the files i am trying to import

**Comment by Parziphal** [comment]
Oh, my bad. I didn't push the commits for some reason. That means that when you ran `composer update` nothing was updated, therefore you got the same error.

Please try doing the same again: edit the `composer.json` file then update the dependencies. Please make sure that something is updated. Then, try importing again.

**Comment by UiharuKazari2008** [comment]
Ok this time i get "a error occurred"
When i ran the update it looked to have retrieved it and is at least failing in a safer manner
![capture696](https://cloud.githubusercontent.com/assets/15165770/17420253/b5271bb0-5a6f-11e6-97e2-c6e1634973b6.png)
`seque@Sequenzia:~/myimouto$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating railsphp/railsphp dev-master (140de21 => 49d3f1f)
    Checking out 49d3f1f697061161d5b2f535bad813826efceff4

Writing lock file
Generating autoload files`

In the log (seque@Sequenzia:~/myimouto$ cat log/production.log) i get:
`[04-Aug-2016 18:12:18 EDT] [192.168.0.49] GET /post/import
Error in Post::get_import_files
Call to undefined function utf8_encode()
#0 app/controllers/PostController.php(1073): Post::get_import_files('/home/seque/myi...')
#1 Rails/ActionController/Base.php(268): PostController->import()
#2 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('import')
#3 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#4 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#5 public/index.php(3): Rails\Application\Base::dispatchRequest()
#6 {main}
Error context:
array(1) {
  [0]=>
  string(40) "/home/seque/myimouto/public/data/import/"
}`
Nothing new in the nginix or php7-fpm log

**Comment by Parziphal** [comment]
Alright, now it's working.

So your PHP is missing a function. Try running:

    sudo apt-get install php7.0-xml

**Comment by UiharuKazari2008** [comment]
Woop that worked! There is another issue with samples but i will post that in a new issues so to not make a mess.

**Comment by Parziphal** [comment]
Alright :D
