### ISSUE TITLE
Samples are larger then orginal image

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#188]
When i post images i am getting samples bigger then the original image
![capture697](https://cloud.githubusercontent.com/assets/15165770/17420586/a987d428-5a71-11e6-9432-4258f6f105b3.png)
![capture698](https://cloud.githubusercontent.com/assets/15165770/17420590/aefacb22-5a71-11e6-9f5d-f56de5e947d6.png)
I think i could be following lines in my config:
`    public $sample_ratio = 0.5;
    public $sample_max = 1500;
    public $sample_min = 1200;
`
Maybe im just setting this wrong and someone can clear my confusion on the sample sizing.

**Comment by UiharuKazari2008** [comment]
Also is there a way to force samples to stay within the limits of the browser window to prevent vertical scrolling?

**Comment by Parziphal** [comment]
This is Danbooru's or Moebooru's configuration, and I've never changed them so I don't exactly understand how they work. But according to the config file...... `$sample_ratio` doesn't mean "make samples 50% of the original image size"; it's used to do calculations that will determine if the system should create a sample. So if I'm not wrong, you're telling the system to create samples if the images are 50% of their own width or height, which means all images will have a sample whose size will be 1500 width max. So your image that seems to be of 771px width ends having a sample of 1500px width.

**Comment by Parziphal** [comment]
As for the second question... I really don't remember if there's an option to do that. I'm searching right now and I can't find something like that.

**Comment by UiharuKazari2008** [comment]
OH that makes sense! 
I also noticed that i cant upload images normally. When i click post the bar goes across but does not advance. When i refresh i see `No service selected/no local service`
Here is my full config if that helps:
[config.txt](https://github.com/myimouto/myimouto/files/402860/config.txt)

**Comment by Parziphal** [comment]
That message is a silly error that appears because there's no "local image search service", I should remove it.

Is there any error logged? Try opening the javascript console (ctrl+shift+j or F12) to check for erros there too.

**Comment by UiharuKazari2008** [comment]
I dont get any messages in firefox but i do get something in the nginx log:
`2016/08/04 18:56:27 [error] 4822#0: *175 client intended to send too large body: 2010910 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 18:56:28 [error] 4822#0: *180 client intended to send too large body: 2010916 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 18:56:29 [error] 4822#0: *179 client intended to send too large body: 2010910 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 18:56:39 [error] 4822#0: *187 client intended to send too large body: 2288434 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 18:56:41 [error] 4822#0: *189 client intended to send too large body: 2288434 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 19:18:28 [error] 4822#0: *193 client intended to send too large body: 3405287 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
2016/08/04 19:18:30 [error] 4822#0: *197 client intended to send too large body: 3405299 bytes, client: 192.168.0.49, server: , request: "POST /post/create.json HTTP/1.1", host: "channel.gakuen-toshi.co.jp", referrer: "http://channel.gakuen-toshi.co.jp/post/upload"
(END)`
nothing in the myimouto log

**Comment by UiharuKazari2008** [comment]
Changing ownership of public/data to www-data:www-data seemed to fix that.
I am assuming the no local image search system has todo with the IQDB thing that danbooru wants

**Comment by UiharuKazari2008** [comment]
You noted that changing the ownership like so is not remembered in the install guide, why is that?

**Comment by UiharuKazari2008** [comment]
Ok so it lets me upload but images that need samples only show the ALT text and will not show any image, i do have a custom prefix set "SAMPLE-Sequenzia-"

**Comment by UiharuKazari2008** [comment]
I get the following error in the production log
You can see i tried diffrent prefixs and even removing the prefix
`[04-Aug-2016 20:37:25 EDT] [192.168.0.49] GET /sample/69df743ed238056922d08d1135c92e83/Sequenzia%20-%2044%20sample.jpg
Not found
No route matches [GET] "/sample/69df743ed238056922d08d1135c92e83/Sequenzia%20-%2044%20sample.jpg"

[04-Aug-2016 20:42:37 EDT] [192.168.0.49] GET /sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg
Not found
No route matches [GET] "/sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg"

[04-Aug-2016 20:42:38 EDT] [192.168.0.49] GET /sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg
Not found
No route matches [GET] "/sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg"

[04-Aug-2016 20:44:39 EDT] [192.168.0.49] GET /sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg
Not found
No route matches [GET] "/sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg"

[04-Aug-2016 20:44:40 EDT] [192.168.0.49] GET /sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg
Not found
No route matches [GET] "/sample/3fef65a0bbbe8e7308e980756f789870/Sequenzia%20-%2060%20sample.jpg"

[04-Aug-2016 20:45:21 EDT] [192.168.0.49] GET /sample/fc1c38a2c939496e5015077636c384c6/Sequenzia%20-%2048%20sample.jpg
Not found
No route matches [GET] "/sample/fc1c38a2c939496e5015077636c384c6/Sequenzia%20-%2048%20sample.jpg"

[04-Aug-2016 20:45:22 EDT] [192.168.0.49] GET /sample/fc1c38a2c939496e5015077636c384c6/Sequenzia%20-%2048%20sample.jpg
Not found
No route matches [GET] "/sample/fc1c38a2c939496e5015077636c384c6/Sequenzia%20-%2048%20sample.jpg"

[04-Aug-2016 20:47:03 EDT] [192.168.0.49] GET /sample/-f25757da479b9387b014dd8e83bbde8d/SAMPLE-Sequenzia%20.jpg
Not found
No route matches [GET] "/sample/-f25757da479b9387b014dd8e83bbde8d/SAMPLE-Sequenzia%20.jpg"

[04-Aug-2016 20:48:01 EDT] [192.168.0.49] GET /sample/64d347ab0bff89ccc7c18a166398c0cc/Sequenzia%20-%2061%20sample.jpg
Not found
No route matches [GET] "/sample/64d347ab0bff89ccc7c18a166398c0cc/Sequenzia%20-%2061%20sample.jpg"

[04-Aug-2016 20:48:02 EDT] [192.168.0.49] GET /sample/64d347ab0bff89ccc7c18a166398c0cc/Sequenzia%20-%2061%20sample.jpg
Not found
No route matches [GET] "/sample/64d347ab0bff89ccc7c18a166398c0cc/Sequenzia%20-%2061%20sample.jpg"

[04-Aug-2016 20:50:25 EDT] [192.168.0.49] GET /sample/8d238998ed983ec49aba9055cd47334d/myimouto%2064%20sample.jpg
Not found
No route matches [GET] "/sample/8d238998ed983ec49aba9055cd47334d/myimouto%2064%20sample.jpg"

[04-Aug-2016 20:50:27 EDT] [192.168.0.49] GET /sample/8d238998ed983ec49aba9055cd47334d/myimouto%2064%20sample.jpg
Not found
No route matches [GET] "/sample/8d238998ed983ec49aba9055cd47334d/myimouto%2064%20sample.jpg"
`

**Comment by Parziphal** [comment]
Oh, your images are larger than the allowed file limit. You need to increase limit for both NGINX and PHP (I'll add this to the guide).

For example, let's increase the limit to 50mb. Open `/etc/nginx/nginx.conf` and inside the `http` block add this:

    client_max_body_size 55M;

Then open `/etc/php/7.0/fpm/pool.d/www.conf` and search for `upload_max_filesize` and set it `50M`, then search for `post_max_size` and set it to `55M`

Then restart both services

    sudo service nginx reload
    sudo service php7.0-fpm reload

---

> I am assuming the no local image search system has todo with the IQDB thing that danbooru wants

Yes, since there's no IQDB service, the system reports that.

> You noted that changing the ownership like so is not remembered in the install guide, why is that?

What do you mean?

**Comment by UiharuKazari2008** [comment]
I forgot to comment back but ya i found that solution late last night and added it to the install guide on the wiki. I also added the php-xml package in the apt-get command
In the install guide in the Wiki the last step tells the user to change to ownership of ../public/data www-data but above it it says that you should only do it on a local installation.

**Comment by Parziphal** [comment]
I made a mistake, the file isn't `/etc/php/7.0/fpm/pool.d/www.conf`, it's `/etc/php/7.0/fpm/php.ini`.

Regarding the ownership, it's only recommended to do that on local installations because for more serious things like public servers, you have to do some changes to the systems users I think...... actualyl I don't remember right now.
