### ISSUE TITLE
Allow Enable Site Notice

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#189]
I noticed that there was a _notice.php file in the layouts folder. Is there a way to enable a site notice? Like "This site contains sexual and grotesque content, please click accept to enter"
That would be really nice :+1:

**Comment by Parziphal** [comment]
I think that's for the topbar notice. The type of notice you mention, which mote like a disclaimer, is not supported. You can add that with just Javascript and a cookie.

**Comment by UiharuKazari2008** [comment]
do you have any suggestions on how i would add that. I would like to add it to the homepage and possibly the post page as well to make sure someone does see it.

**Comment by Parziphal** [comment]
Right now I can't write a full response. I'll help you tomorrow if you haven't found a solution till then. My simple idea is something like check a cookie, if it doesn't exist show a  container with the notice and a couple buttons to either accept or cancel. Accept will create the cookie and hide the notice, and cancel will send the user somewhere else. Really simple.

**Comment by UiharuKazari2008** [comment]
ok i can wait till tommarow as right now im spending most of my time importing pictures.
Im pretty new to php and js, i spend most of my time in python, bash, and powershell

**Comment by Parziphal** [comment]
Ok this is a very basic thing but it works...

Add the below code somewhere after the body tag in `app/views/layouts/default.php` and other layout files.

```html
<script>
(function() {
  var cookieName = 'disclaimer_accepted';

  if (Cookie.get(cookieName)) {
    return;
  }

  var $ = jQuery;
  var notice = 'This is my disclaimer, do you accept?';
  var ok = 'Accept';
  var cancel = 'Cancel';

  var container = $('<div>')
    .css({
      backgroundColor: 'rgba(0,0,0,0.8)',
      width: '100%',
      height: '100%',
      position: 'absolute',
      left: 0,
      top: 0,
      zIndex: 999,
    });
  
  container.append(
      $('<div>')
        .css({
          display: 'flex',
          width: '100%',
          height: '100%',
          justifyContent: 'center',
          alignItems: 'center',
        })
        .append(
          $('<div>')
            .css({
              backgroundColor: 'white',
              display: 'flex',
              padding: 8,
              minWidth: 350,
              flexDirection: 'column'
            })
            .append(
              $('<div>')
                .css({
                  margin: 8,
                  color: 'black'
                })
                .html(notice)
            )
            .append(
              $('<div>')
                .css({
                  margin: 8,
                  textAlign: 'right'
                })
                .append(
                  $('<button>')
                    .css({
                      marginRight: 5
                    })
                    .html(ok)
                    .click(function() {
                      Cookie.put(cookieName, true);
                      container.remove();
                    })
                )
                .append(
                  $('<button>')
                    .html(cancel)
                    .click(function() {
                      window.location.href = 'about:blank';
                    })
                )
            )
        )
    )
    .prependTo(
      $('body')
    )
})();
</script>
```

**Comment by UiharuKazari2008** [comment]
Woop! That worked! Thanks!
