### ISSUE TITLE
Apache Reverse Proxy with SSH Port Forwarding

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#190]
I use a SSH port forwarding to allow access to internal servers with Apache reverse proxing.
How would you setup access behind a Apache reverse proxy, is it even possible?
[https://acr.moe/seq] --- Magic SSH Tunnel --->[http://channel.gakuen-toshi.co.jp/]
            Public        -L 6007:channel.gakuen-toshi.co.jp:80        Intranet

Is there a way that i can still access it from both addresses

**Comment by Parziphal** [comment]
I'm sorry this goes beyond my knowledge... and beyond the scope of these issues actually.
