### ISSUE TITLE
Option tag_subscription_post_limit in config not working?

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#191]
Maybe I'm doing something wrong, but I have it set to 300 yet tag subs only show 100 posts in your profile. That's even less than the default of 200. Is there a bug somewhere or am I mistaken in what this option is supposed to do?

**Comment by Parziphal** [comment]
Sorry, I can't understand what you mean.

**Comment by Ma-ryan** [comment]
I want to increase the amount of posts cached by tag subscriptions to 300. When you view your subscribed posts, there are only 100 by default. Is there any way to increase them?

**Comment by Parziphal** [comment]
For some reason, the `tag_subscription_post_limit` is divided by 3. Why? I have no idea, it's not documented in the config. So if you want 300, set the limit to 900.

I think that division should be removed shouldn't it? I don't know what's behind it.

**Comment by Parziphal** [comment]
I closed this a little soon...

What do you mean that "only show 100 posts in your profile"? In the profile are shown only the latest 5 posts of everything (uploads, favorites, subs, etc).

**Comment by Ma-ryan** [comment]
I mean when you access your tag sub from your profile. (e.g. ```sub:SomeUser:Tagsub``` in the search bar)

100 posts makes sense now that you mention it's divided by 3. Since I put 300 as my limit, I got 100 posts. Though I'm not sure about the logic behind it. So for each tag I put in my sub, I get 100 posts, and a total of 1000 posts for all tags combined?

**Comment by Parziphal** [comment]
The system will search for all latest posts with each tag, and the grand total will be your `limit`.

Say you have a limit of **120** and a query of **4** tags. The system will find a max of `4 * (120 / 3) = 160` posts, then it will remove the duplicates, then it will order them by id (latest first), then it will keep only the first 120. If only 2 tags out of the 4 had posts, then you'll get a max of 80 posts. If some posts were tagged with both tags, you'll get less than 80. Or if one tag had only 10 posts, another had 15 and the rest had 0, then you'll get 25 posts.

So in your case, your query either had only 1 tag, or from all the tags only 1 had posts.
