### ISSUE TITLE
Nameless tag subscription causes error

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#192]
I noticed some users were doing this. If you make a tag sub without a name (put tags only), and when you try to access it from your profile (click the link), MyImouto would crash.

Error from the log:

```
GET /post?tags=sub%3Atheotherguy%3A
PHP Notice in Post::generate_sql
Undefined offset: 1 
#0 app/models/Post/SqlMethods.php(169): Rails::errorHandler(8, 'Undefined offse...', '/home/booru...', 169, Array)
#1 app/models/Post/CountMethods.php(12): Post::generate_sql('sub:theotherguy...', Array)
#2 Rails/Cache/Cache.php(85): Post::{closure}()
#3 app/models/Post/CountMethods.php(15): Rails\Cache\Cache->fetch(Array, Object(Closure))
#4 app/controllers/PostController.php(359): Post::fast_count('sub:theotherguy...')
#5 Rails/ActionController/Base.php(268): PostController->index()
#6 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('index')
#7 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#8 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#9 public/index.php(3): Rails\Application\Base::dispatchRequest()
#10 {main}
Error context:
```

My suggestion would be to make naming your tag sub a requirement.

Edit: It looks like you can even make a tag sub with BOTH name and tag fields empty! That's pretty crazy and should be fixed.

**Comment by Parziphal** [comment]
...wait, that won't fix it, that broke it, my bad.

**Comment by Parziphal** [comment]
The tag subscriptions are now created with a default name "new_tagsub". The tag query being empty doesn't matter, but I also added a `require` attribute on text fields so the user must enter a name and a query in order to update their subscriptions. This restriction can be easily bypassed though.
