### ISSUE TITLE
Troubleshooting database configuration

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#193]
I have a MySQL server that i pointed my myimouto server to and all is fine but i want to setup another server that is at another location (but has access back to the main network via a IPSec router). When i installed the server and duplicated the config i get a 500 server on the new server. They have a common /public/data directory via CIFS.
I get nothing in the nginx or php logs, I do get a error from the production.log saying

```
[17-Aug-2016 11:58:45 EDT]
Symfony\Component\Yaml\Exception\ParseException in Rails\Yaml\Parser#read
Error while reading file /home/sequenzia/myimouto/config/database.yml:
Unable to parse "/home/sequenzia/myimouto/config/database.yml" as the file is not readable.
#0 Rails/Yaml/Parser.php(14): Rails\Yaml\Parser->read()
#1 Rails/Application/Base.php(265): Rails\Yaml\Parser::readFile('/home/sequenzia...')
#2 Rails/Application/Base.php(106): Rails\Application\Base->_load_active_record()
#3 Rails/Application/Base.php(50): Rails\Application\Base->boot()
#4 config/boot.php(29): Rails\Application\Base::initialize()
#5 public/index.php(2): require('/home/sequenzia...')
#6 {main}
Error context:
```

The contents of the file is: 

```
login: &login
  adapter: mysql
  host: some-host
  username: root
  password: shut!!!
```

**Comment by Parziphal** [comment]
"The file is not readable", it sounds like permission problems, check on that.

**Comment by UiharuKazari2008** [comment]
Fixed the permissons and now i get 

> [17-Aug-2016 12:30:21 EDT] [192.168.0.49] GET /
> Rails\ActiveRecord\Exception\RuntimeException in Rails\ActiveRecord\ActiveRecord::connection
> No database connection is active
> #0 Rails/ActiveRecord/Base.php(172): Rails\ActiveRecord\ActiveRecord::connection(NULL)
> #1 Rails/ActiveRecord/Base/Methods/ModelSchemaMethods.php(48): Rails\ActiveRecord\Base::connection()
> #2 Rails/ActiveRecord/Base/Methods/ModelSchemaMethods.php(16): Rails\ActiveRecord\Base::initTable()
> #3 Rails/ActiveRecord/Base/Methods/AttributeMethods.php(334): Rails\ActiveRecord\Base::table()
> #4 Rails/ActiveRecord/Base.php(253): Rails\ActiveRecord\Base->setDefaultAttributes()
> #5 app/controllers/ApplicationController.php(102): Rails\ActiveRecord\Base->__construct()
> #6 Rails/ActionController/Base.php(464): ApplicationController->set_current_user()
> #7 Rails/ActionController/Base.php(230): Rails\ActionController\Base->runFilters('before')
> #8 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
> #9 Rails/Application/Base.php(39): Rails\Application\Base->_run()
> #10 public/index.php(3): Rails\Application\Base::dispatchRequest()
> #11 {main}
> Error context:
> array(1) {
>   [0]=>
>   NULL
> }

I updated the Grants on the database and can now login via mysql in the command line

**Comment by Parziphal** [comment]
Your file should look like this:

```
production:
  adapter: mysql
  host: nix-database.public.gakuen-toshi.co.jp
  username: root
  password: shut!!!
  database: myimouto
```

It seems like you removed the two keys (development and production) after `login: &login`.

**Comment by UiharuKazari2008** [comment]
Yep that was it, all is fair now. Is there any dangers of using 2 servers with a common database and data storage?

**Comment by Parziphal** [comment]
I'm not an expert on that... but I'd say that the risks would be the same as using one server, right? Except that if one server gets compromised, the other one will get hit as well.
