### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by UiharuKazari2008** [myimouto/myimouto#195]
I have a few feature requests:
- Automatic Import? Maybe a cron job that automatically imports images, im assuming there would also need to be folders for each rating.
- Mass Edit Tags from Tags page, When on tags page and maybe a mass edit button is pressed all the types would be drop down menus to change them all at once, and maybe all the tags names become input boxes so they can be renamed.
- When on Apply Tag Script, a "apply to all" button or selection boxes with select all and apply
- Keyboard shortcuts like on danbooru (example: ,"right arrow key" will go to next image)

**Comment by Parziphal** [comment]
Sadly, I'm not developing this system anymore, I'm only fixing things.

**Comment by rmrhz** [comment]
@Parziphal Can you still access merge requests?

**Comment by Parziphal** [comment]
I'm sorry, but I've decided not to support this project anymore, even with PRs.
