### ISSUE TITLE
PDO could not find driver

### ISSUE THREAD

**Issue by Yushe** [myimouto/myimouto#196]
It said this when I tried to run <code>php install.php</code>

```
*** PDOException in PDO#__construct ***
could not find driver
#0 Rails/ActiveRecord/Connection.php(273): PDO->__construct('mysql:host=loca...', 'root', 'password', Array)
#1 Rails/ActiveRecord/Connection.php(31): Rails\ActiveRecord\Connection->create_connection(Array)
#2 Rails/ActiveRecord/ActiveRecord.php(74): Rails\ActiveRecord\Connection->__construct(Array, 'production')
#3 Rails/ActiveRecord/ActiveRecord.php(60): Rails\ActiveRecord\ActiveRecord::create_connection('production')
#4 Rails/ActiveRecord/ActiveRecord.php(109): Rails\ActiveRecord\ActiveRecord::setConnection('production')
#5 Rails/ActiveRecord/Migration/Migrator.php(15): Rails\ActiveRecord\ActiveRecord::connection()
#6 install.php(13): Rails\ActiveRecord\Migration\Migrator->__construct()
#7 {main}
Error context:
```

**Comment by Parziphal** [comment]
Please see #172.

**Comment by Yushe** [comment]
@Parziphal I have php5-mysql installed and I'm using php 7 like the install page says, I even checked php5 is not installed.

**Comment by Parziphal** [comment]
Then try:

    sudo apt-get install php7-mysql

**Comment by Yushe** [comment]
@Parziphal <code>E: Unable to locate package php7-mysql</code>

**Comment by Parziphal** [comment]
`php7.0-mysql` ?

**Comment by Yushe** [comment]
@Parziphal Hmm... it seems I already have that installed as well. <code>php7.0-mysql is already the newest version.</code>

**Comment by Parziphal** [comment]
Well I don't know... restart php, or make sure the extension is enabled.

**Comment by Parziphal** [comment]
What do you see when you run `php -v`?

**Comment by Yushe** [comment]
@Parziphal <code>PHP 7.0.10-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies</code>

**Comment by Parziphal** [comment]
How about... make sure that you have a file like `20-pdo_mysql.ini` in `/etc/php/7.0/cli/conf.d`?

**Comment by Yushe** [comment]
I have that file in that directory.

**Comment by Parziphal** [comment]
Strange... Try creating a PHP file inside de `public` directory, then add this:

```php
<?php
new PDO("mysql:host=127.0.0.1");
```

and access it from your browser. What do you see?

**Comment by Yushe** [comment]
I've got it sorta working now the page is showing up blank.

**Comment by Parziphal** [comment]
What do you see in the log file?

**Comment by Yushe** [comment]
<code>[Mon Aug 29 01:30:21.145494 2016] [:error] [pid 1071] [client 180.76.15.144:19784] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'fopen(/var/www/html/myimouto/log/production.log): failed to open stream: Permission denied' in /var/www/html/myimouto/vendor/zendframework/zend-log/src/Writer/Stream.php:79\nStack trace:\n#0 [internal function]: Zend\\Stdlib\\ErrorHandler::addError(2, 'fopen(/var/www/...', '/var/www/html/m...', 79, Array)\n#1 /var/www/html/myimouto/vendor/zendframework/zend-log/src/Writer/Stream.php(79): fopen('/var/www/html/m...', 'a', false)\n#2 /var/www/html/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(456): Zend\\Log\\Writer\\Stream->__construct('/var/www/html/m...')\n#3 /var/www/html/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(155): Rails::defaultLogger()\n#4 /var/www/html/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(308): Rails::log()\n#5 /var/www/html/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(268): Rails::reportException(Object(Rails\\Exception\\PHPError\\Warning))\n#6 [internal function]: Rails::exceptionHandler(Object(Rails\\Exception\\PHPError\\W in /var/www/html/myimouto/vendor/zendframework/zend-log/src/Writer/Stream.php on line 82</code>

**Comment by Parziphal** [comment]
You missed the last step on the install guide that sets permissions to files. If you're using your site locally, run:

```
chmod -R 0777 log tmp
sudo chown -R www-data:www-data public/data/
```

**Comment by Yushe** [comment]
The homepage is now showing but the links like posts is not found...

**Comment by Parziphal** [comment]
It seems like you haven't setup your server for redirection. Please follow the guide carefuly.

**Comment by Yushe** [comment]
I just checked and for some reason my server has decided to not use .htaccess again. :/

Thanks for the help!
