### ISSUE TITLE
How to have multiple $server_hosts

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#197]
In my config.php file, I have it set up to where I can access the website from outside my network through my ddns provider, but I would still like to be able to access my website from the local network. How could I set 2 `$server_host`s in the config file?

**Comment by Parziphal** [comment]
I can think of some ways, but maybe the easiest would be to detect that you're connecting from local network and change the `$server_host` to the local value that you want. You could do so by adding this to your `config.php`:

```php
class LocalConfig extends DefaultConfig
{
    // etc...

    public function __construct()
    {
        if (strpos($_SERVER['REMOTE_ADDR'], '192.168.') === 0) {
            $this->server_host = 'your-local-host';
        }
    }
}
```

**Comment by Justawinterwolf2012** [comment]
I tried to use the code that you provided above, but this is what happened:

![config php_007](https://cloud.githubusercontent.com/assets/16302135/18076171/63b58e5e-6e30-11e6-8e9c-321ce34a94fb.png)
![error - mozilla firefox_008](https://cloud.githubusercontent.com/assets/16302135/18076175/67d2128c-6e30-11e6-8843-71a14bf6d268.png)

**Comment by Justawinterwolf2012** [comment]
And looking over the code again, now I'm getting this error:

`Fatal error: Cannot redeclare MyImouto\LocalConfig::__construct() in /home/blahblah/myimouto/config/config.php on line 33`

**Comment by Justawinterwolf2012** [comment]
Okay, after moving the `public function __construct()` section to add a new set of tag types to my default_config.php file, the code you gave me above works... kind of.

Now I'm having a problem where I can't see any pictures in the booru, whether it's from my local IP address, or an external one. Here's how I employed your code:

`    public function __construct() {
        if (strpos($_SERVER['REMOTE_ADDR'], '192.168.') === 0) {
            $this->server_host = '192.168.1.202:3000';
        }
    }`

**Comment by Justawinterwolf2012** [comment]
Heh heh... I made a typo while typing in my public address. I think I'll just close this now... Thank you for the fix!

**Comment by Parziphal** [comment]
Consider changing also `url_base` along with `server_host`. I don't remember where it is used but you may need it changed too.
