### ISSUE TITLE
Upload images to myimouto using cURL.

### ISSUE THREAD

**Issue by Shir01** [myimouto/myimouto#198]
Hi.
I would like to know if it is possible to upload images to myimouto using command-line tool cURL? And if it is, what syntax should I use? 

According to "API" section in "Help" a command like this:
`curl -F "login=Username" -F "password_hash=pass_hash value from the cookie file" -F "post[tags]=1girl mermaid sakimichan" -F "post[file]=@C:\00\33.jpg" -F "post[rating]=safe" localhost:3000/post/create`
should work, but it doesn't and I don't  have sufficient knowledge to understand why.

Could you please help?

**Comment by Parziphal** [comment]
This successfuly worked for me:

```
curl -X POST\
  -H "Cache-Control: no-cache"\
  -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW"\
  -F "user[name]=USERNAME"\
  -F "user[password]=PASSWORD"\
  -F "post[source]="\
  -F "post[tags]=artist:parziphal"\
  -F "post[parent_id]="\
  -F "post[rating]=s"\
  -F "post[file]=@"\
  "http://192.168.0.35:3000/post/create.json"
```

Source and parent_id are, of course, optional.

**Comment by Shir01** [comment]
@Parziphal 
Indeed this works. Thank you very much, you've helped me a lot. :)

**Comment by Parziphal** [comment]
:)
