### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#199]
The posts with the rating e are only visible. All other posts that have the rating q and s aren't visible. I don't know why.. ,_,

**Comment by Parziphal** [comment]
Me neither.

Have you made any changes to anything? CSS maybe?

**Comment by Kille250** [comment]
Only added a video line with max-height. But it should effect the post ratings ,_,

**Comment by Kille250** [comment]
Shouldn't*

**Comment by Parziphal** [comment]
Open the developers tools (right click > Inspect element) and try to locate a hidden post. Check its CSS properties, or take a screenshot of the properties and post it here.

**Comment by Kille250** [comment]
http://dioderplayboy.xyz/data/jpeg/55452b846eadaa66ab68d89a04b4e7b5.jpg

**Comment by Parziphal** [comment]
So it's on the "show" page where they don't show? They only show a white background? And you're on your phone? I keep forgetting a lot of people use phones, I'm always on a computer.

Ok so it looks like you _can't_ see that post. It seems like you made an inverted logic on your config, on the `can_see_post` method. Looks like you wanted to hide only E, but instead you're showing only E.

**Comment by Kille250** [comment]
It's wierd. They don't show in the index, also the error message appear. If you visit the site without beeing logged in you don't will see the pictures with the rating e. whut is going on

**Comment by Kille250** [comment]
alright, i removed the line and now nothing appears.. wtf xD

**Comment by Parziphal** [comment]
That `#post.show_partials.image.text` message (which is actually a missing translation) appears when the user can't see that post according to configuration. What do you have in your `can_see_post` config method?

**Comment by Kille250** [comment]
# Determine who can see a post.
    public function can_see_post(\User $user, \Post $post)
    {
        # By default, no posts are hidden.

        if ($post->rating == 'e' && $user->is_privileged_or_higher()) return true;
        if ($post->rating == 's' && $user->is_member_or_higher()) return true;

        # Some examples:
        #
        # Hide post if user isn't privileged and post is not safe:
        # if ($post->rating == 'e' && $user->is_privileged_or_higher()) return true;
        #
        # Hide post if user isn't a mod and post has the loli tag:
        # if ($post->has_tag('loli') && $user->is_mod_or_higher()) return true;
    }

**Comment by Parziphal** [comment]
Try this:

```php
if ($user->is_privileged_or_higher()) {
    return true;
} elseif ($post->rating != 'e') {
    return true;
}
```

This says that privileged and higher can see any picture, and everyone else can see anything but E.

**Comment by Kille250** [comment]
yep, it's working. Thanks! :^)

**Comment by Kille250** [comment]
Another question. How can i restrict access on the history page, because the preview pictures are shown if you hover over the links. The law here doesn't allow that ,-,

**Comment by Parziphal** [comment]
That's an interesting point. I made a change to the history page. Apply that change and see if it works as intended.

**Comment by Kille250** [comment]
you'r a god. xD
