### ISSUE TITLE
Last question for now

### ISSUE THREAD

**Issue by Kille250** [myimouto/myimouto#200]

**Comment by Kille250** [comment]
Is it possible to load all the safe pictures in one page. I read a issue from long ago and you said the database would take a little bit to load all the informations. But i think new users would be better on my imageboard if it would be possible. :c

**Comment by UiharuKazari2008** [comment]
What exactly do you mean? Load more images per page or only show safe?
Load more images per page:
`nano ~/myimouto/config/config.php`
add `public $post_index_default_limit = 250;` and "250" is the amount to load.
NOTE: This is NOT recommend for a public site, this works fine on a local network but be careful.
Show only safe images:
Search String: "rating:safe"

**Comment by Kille250** [comment]
Look. If a normal user visit my page the safe images will be somewhere in the 20 pages. I want that the index page will automatically load all safe or questionable "items" in the first page without typing "rating:quastionable" to make this userfriendly. Can you follow my question? ,_,

**Comment by UiharuKazari2008** [comment]
I kinda follow, let me know if this helps:

**If you also mean block everything except safe:**
There are 2 ways, I have 2 servers 1 local and 1 remote but they both use shared database and data storage. I have my local completely open while the remote one requires login to access some tags and defaults to blacklisting non safe images.
**Here is how:**
**Meathod 1 - Require membership or specific level:**
>     public function can_see_post(\User $user, \Post $post)
>     {
>         return true;
>         if ($post->rating == 'e' && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('loli') && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('rape') && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('guro') && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('cate2') && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('cate3') && $user->is_member_or_higher()) return true;
>         if ($post->has_tag('cate4') && $user->is_member_or_higher()) return true;
>     }
Here you can see that it requires membership to even access erotic images but also restricts access to cate*, loli, guro, rape. I prefer this method as it makes sure there is no way internet users and Google (i mean Skynet) can access the images. You can change is_member_or_higher to any level you want. Refer to default_config for levels.
**Method 2 - Blacklists:** 
>     public $default_blacklists = array (
>         "cate2","guro","rape"
>     );
Blacklists are a "soft" block that a user can override by expanding the "Hidden Posts" link or editing there settings to non block them. You can put any tag or supported query to remove them,
Both ways removed the images from the page. 
Blacklists will leave a gap while the meathod 1 will not leave gaps as it pulls them from search query.
You can see this in action at my public board: https://sequen.acr.moe

**Comment by UiharuKazari2008** [comment]
Edit: Well then i guess thats not working..... For some reason its showing them even without membership. May be a bug

**Comment by Kille250** [comment]
Nja, i know that already. I only want that the gaps from the posts that are hidden will be replaced with viewable content. If you visit http://dioderplayboy.xyz you will see what i mean. The first page will show nothing and i want that the safe content or allowed content will be load automatically there. But thank you for trying to help me! =)

**Comment by UiharuKazari2008** [comment]
Oh i see whats going on here. Did you delete the prior posts because it looks like that could be cause. I can tell because there are no blacklists and if i can to a random prior ID i get 

> #post.show_partials.image.text

Which looks strange because you should get a "This post is deleted" type banner. What do your production logs say?

**Comment by Kille250** [comment]
Nah it's fine. It's a translation error. You can only see the posts with the member role preveleged. :^) And to get mp4 working. Search webm support in the ticket section :D

**Comment by Parziphal** [comment]
@Kille250 lol, all images are blocked from your index. Congrats on issue Nº 200! Have a cookie :cookie:!

This question is similar to the one you mentioned (which is the very first issue actually). In your case, your best option would be to switch the default search query according to the currently connected user. The default query is built in `app/models/Post/SqlMethods.php`.

This differs from the other question in which the inquirer wanted to _fill_ the gap created by blocked posts. Well, his best option would have been also to have custom default queries... I guess I didn't think of that back then.

@UiharuKazari2008 your `can_see_post` method has a `return true;` on the top, which prevents the code below to be executed; that makes all images visible for everyone. You can have a cookie too! :cookie:

**Comment by Kille250** [comment]
How can i do this? xD

**Comment by Kille250** [comment]
And again, i eant to thank you for helping me on every issue that i had. You'r a very nice person!

**Comment by Parziphal** [comment]
You're welcome. However, for this case, you will have to think on your own implementation yourself. You can do something like:

```php
if (!current_user()->is_member_or_higher()) {
    $q['exclude'] = array_merge($q['exclude'], ['default_excluded_1', 'default_exluded_2', ...]);
}
```

But then you'll have to change the logic about the tag limit on lines `256` and `268`. And now that I think about it, this could hinder performance a little, since it's excluding posts.

**Comment by Kille250** [comment]
Ouh shit, i will try that. But thank you for this hint.

**Comment by Kille250** [comment]
For what does default_exluded_1 and 2 stand?

**Comment by Parziphal** [comment]
They stand for tags you want to exclude from results... but you want to exclude by rating right? That would make things easier. I think this should work:

```php
# line 117
$conds = array('true');

if (!current_user()->is_member_or_higher()) {
    $conds[] = 'p.rating != "e"';
}

# line 286
if (is_string($q['rating'])) {
    $r = strtolower(substr($q['rating'], 0, 1));
    if ($r == "s")
        $conds[] = "p.rating = 's'";
    elseif ($r == "q")
        $conds[] = "p.rating = 'q'";
    elseif ($r == "e" && current_user()->is_member_or_higher())  // Make sure user is member or higher here too
        $conds[] = "p.rating = 'e'";
}
```

That is supposed to hide "e" posts.

**Comment by Kille250** [comment]
I hate my life. I don't have that knowledge to know that all. How did you start to learn this? ,-,

**Comment by Parziphal** [comment]
I updated the code above because there would have been a conflict if an anonymous user searched for specific rated posts. Now there should be no conflict. It was confusing...

I [started](http://pop-works.blogspot.pe/2011/03/danbooru-imouto-emulator-for-php.html) to learn web development precisely with this project! I wanted to have my own local "moe.imouto.org" (back then) so I took this other booru software called "Naranai" and started to change it to make it look and behave like Moebooru. I only had basic HTML knowledge and a vague notion of PHP and MySQL. It took me about a month of 10+ hours per day (I had no job back then) to bring the system to an usable state.

As I learned more I wrote my own "PHP framework" and that helped me to learn even more. But since I was learning on my own, I made tons of mistakes, and proof of it is the framework itself: it's a mess.

Thus, and thanks to God, I became a programmer. lol. And I kept learning but I had to leave this project behind, so it stayed like this. At least it still works.

On a side note, I wanted my own local booru because back then  [I was into drawing](http://hajimete.deviantart.com), so I had a couple thousands pics laying around on my disk, and I wanted an easier way to search for a specific image, like on a booru. Then, I moved out of drawing because of programming. One thing led to another. Funny huh?

**Comment by Kille250** [comment]
You'r awesome. I go to a vocational school and learn there c# and other network related things. I don't know how to start learning programming. ,-,

**Comment by Kille250** [comment]
btw i have an other problem. 

I got:

[03-Sep-2016 21:31:39 CEST] [84.119.160.239] GET /user/show/4
PHP Warning
mkdir(): Permission denied 
#0 [internal function]: Rails::errorHandler(2, 'mkdir(): Permis...', 'Rails/Cache/Sto...', 79, Array)
#1 Rails/Cache/Store/FileStore/Entry.php(79): mkdir('/opt/lampp/htdo...', 511, true)
#2 Rails/Cache/Store/FileStore.php(27): Rails\Cache\Store\FileStore\Entry->write(Array)
#3 Rails/Cache/Cache.php(54): Rails\Cache\Store\FileStore->write('favorite_tags/4...', Array, Array)
#4 app/models/User.php(356): Rails\Cache\Cache->write('favorite_tags/4...', Array, Array)
#5 app/views/user/show.php(130): User->voted_tags(Array)
#6 Rails/ActionView/Template.php(229): require('/opt/lampp/htdo...')
#7 Rails/ActionView/Template.php(121): Rails\ActionView\Template->_init_render()
#8 Rails/ActionController/Response/Template.php(40): Rails\ActionView\Template->renderContent()
#9 Rails/ActionController/Response/Base.php(15): Rails\ActionController\Response\Template->_render_view()
#10 Rails/ActionController/Base.php(716): Rails\ActionController\Response\Base->render_view()
#11 Rails/ActionController/Base.php(247): Rails\ActionController\Base->_create_response_body()
#12 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#13 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#14 public/index.php(3): Rails\Application\Base::dispatchRequest()
#15 {main}
Error context:
array(4) {
  ["val"]=>
  array(0) {
  }
  ["header"]=>
  string(21) "expires_in=1473017499"
  ["v"]=>
  int(1473017499)
  ["k"]=>
  string(10) "expires_in"

I can't visit a users profile. It says a problem occurs. Is sth wrong with the permissions?

**Comment by Kille250** [comment]
nvm got it fixed
