### ISSUE TITLE
How to relocate /data/image/* to subdomain

### ISSUE THREAD

**Issue by Justawinterwolf2012** [myimouto/myimouto#202]
I'm a frequent user of a certain Danbooru-based booru that somehow relocated their /data/image/* folders to `static.example.com/data/image` instead of `example.com/data/image`. Is there any way to do this with MyImouto?

**Comment by Parziphal** [comment]
I think you could create your own image story class... it could extend `Post_ImageStore_LocalHierarchy` (`app/models/Post/ImageStore/LocalHierarchy.php`), let's call it `SubDomainHierarchy.php`, and change every `CONFIG()->url_base` with something like `CONFIG()->image_host`, which would be a new config option you'd create, which would be a string like `http://static.example.com`. Then use that store by setting `$image_store = 'sub_domain_hierarchy';` on your config.

But I believe that this, besides having a subdomain in the url, wouldn't affect anything in any way. They probably have a different server where they are storing their static content, or who knows why they changed it.

**Comment by Justawinterwolf2012** [comment]
In the new SubDomainHierarchy.php file, would it just be a matter of copying the public classes of LocalHeirarchy.php and replacing the `CONFIG()->url_base`s with `CONFIG()->image_host`s?

**Comment by Parziphal** [comment]
Yes, that should do it.

**Comment by Justawinterwolf2012** [comment]
I tried doing that, but I can't seem to get it to work. Here's how I configured it:

<?php
class Post_ImageStore_SubDomainHierarchy extends Post_ImageStore_LocalHierarchy
{

public function file_url()
    {
        if (CONFIG()->use_pretty_image_urls)
            return CONFIG()->image_host . "/image/".$this->_post->md5."/".$this->_post->pretty_file_name().".".$this->_post->file_ext;
        else
            return CONFIG()->image_host . "/data/image/".$this->_post->file_name();
    }

public function preview_url()
    {
        if ($this->_post->status == "deleted")
            return CONFIG()->image_host . "/deleted-preview.png";
        elseif ($this->_post->image())
            return CONFIG()->image_host . "/data/preview/".$this->_post->md5.".jpg";
        else
            return CONFIG()->image_host . "/download-preview.png";
    }

    public function store_jpeg_url()
    {
         if (CONFIG()->use_pretty_image_urls) {
            return CONFIG()->image_host . "/jpeg/".$this->_post->md5."/".$this->_post->pretty_file_name(array('type' => 'jpeg')).".jpg";
        } else {
            return CONFIG()->image_host . "/data/jpeg/".$this->_post->md5.".jpg";
        }
    }

    public function store_sample_url()
    {
         if (CONFIG()->use_pretty_image_urls) {
            $path = "/sample/".$this->_post->md5."/".$this->_post->pretty_file_name(array('type' => 'sample')).".jpg";
        } else {
            $path = "/data/sample/" . CONFIG()->sample_filename_prefix . $this->_post->md5.".jpg";
        }

        return CONFIG()->image_host . $path;
    }
}

**Comment by Parziphal** [comment]
What error are you getting?
